### ISSUE TITLE
small integration request 

### ISSUE THREAD

**Issue by mcpecommander** [TheUnderTaker11/GeneticsReborn#10]
Since you seem to know how make JEI integration , I have a small request: can you please add a small info tab to each machine showing how can they be used because I never used "advanced genetics" before and I took some time to understand how some machines work

**Comment by TheUnderTaker11** [comment]
Would gray textures of the items you should be putting in an getting out in the GUI slots be good enough? I thought my wiki would of explained that well.

**Comment by mcpecommander** [comment]
Yea that would be great, and I might do an improved texture to the gui if machines and show it to you later

**Comment by mcpecommander** [comment]
Of the machines *

**Comment by TheUnderTaker11** [comment]
Alright, and if you want to just communicate directly I just made a discord here https://discord.gg/CctRSCk

**Comment by TheUnderTaker11** [comment]
Done, version 0.15 is out
