### ISSUE TITLE
[1.12.2] Putting more than one DNA Helix in a Plasmid Infuser will only add 'one' towards a Gene while deleting the rest.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#100]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 6
BrandonsCore-1.12.2-2.4.17.208-universal
CodeChickenLib-1.12.2-3.2.3.358-universal
Draconic-Evolution-1.12.2-2.3.24.349-universal
geneticsreborn-1.12-1.15
jei_1.12.2-4.15.0.291
RedstoneFlux-1.12-2.1.0.6-universal

-----

Note:
Draconic Evolution was added just so I have a power source to work with.

The Plasmid Infuser apparently doesn't like it when you put in more than one DNA Helix inside it. Upon doing this... only one of the Helix will apply towards getting a Gene while the rest of them are deleted.
![](https://cdn.discordapp.com/attachments/377171551155650560/640779271547256845/genereborndnahelixstackdelete.PNG)

Left: I have 3 'Scare Skeletions' Helix, ready to put them inside the Plasmid Infuser.

Right: I put in 3 'Scare Skeletions' Helix inside the infuser and only one of the counted while the rest were deleted. If all three counted... it would show '6/24'. 'Not 2/24'

**Comment by clubpetey** [comment]
fixed in next release.
