### ISSUE TITLE
[1.12.2] Adding all Genes via commands will cause a crash loop.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#101]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 2
geneticsreborn-1.12-1.15
jei_1.12.2-4.15.0.291

Crash Report:
https://pastebin.com/BTRxnH4Q

-----

I am unsure if this can occur without commands but figure I report it regardless. If you give yourself all the genes via commands... the game will get stuck in a crash loop.

P.S.
Could pressing the TAB key show a list of genes to add? It currently doesn't do that beyond 'add' & 'remove' which would make it easy to see which gene or a combination of genes that are causing the crash to occur.

**Comment by clubpetey** [comment]
fixed in next version.  Issue was with genes that had a cooldown.
