### ISSUE TITLE
Missing Mutation pages in the wiki (Edit: found a typo)

### ISSUE THREAD

**Issue by Wxrlds** [TheUnderTaker11/GeneticsReborn#102]
The wiki says the resistance and flight gene are available for mutations. If you click on the wiki page for flight and resistance, they won't say anything about mutations
Edit: Also found a typo in the mutations wiki page:
Potion of Mutation: Tier II potion, used as a base potion for getting ***a noverpowered***

**Comment by clubpetey** [comment]
fixed the typo and added mutation notes.
