### ISSUE TITLE
[1.12.2] Creative mode delete item slot

### ISSUE THREAD

**Issue by Wxrlds** [TheUnderTaker11/GeneticsReborn#103]
There is an item in the delete item slot. I don't know if this is your fault or some other mods but after I updated the mod to 1.15 it appeared.
![grafik](https://user-images.githubusercontent.com/42120270/68144030-0a232080-ff33-11e9-832e-00f38b5f9ef9.png)

**Comment by clubpetey** [comment]
Oh, weird... that's our mod, but not sure how I'm doing that... I will check it out.

**Comment by TheUnderTaker11** [comment]
Happens when you register items with varients and don't manually check
creative tab.

**Comment by clubpetey** [comment]
Yep, exactly right, corrected.
