### ISSUE TITLE
CraftTweaker 2 NullPointer

### ISSUE THREAD

**Issue by Daedalusia** [TheUnderTaker11/GeneticsReborn#104]
https://pastebin.com/WHsAxwun

Cheers!

**Comment by clubpetey** [comment]
This error is generated by a potion without an NBTtag, which in the vanilla game should not happen.  Are you using CraftTweaker to create any custom potions or brewing recipes?

**Comment by Daedalusia** [comment]
I honestly wouldn't know as this is an Enigmatica 2 modpack which I then added like 300 mods onto. I haven't configured those 300 mods in anyway and never added anything into CraftTweaker so would Enigmatica's recipes be the likely cause? Cheers

**Comment by clubpetey** [comment]
Ok, I'll patch what I think this is in 1.17, but let me know if I fix it, I cannot reproduce this.

**Comment by Daedalusia** [comment]
Got it, I'm gonna try it right now, thank you!

**Comment by Daedalusia** [comment]
Just wanted to let you know the game loaded successfully! Thank you so much! Time to test the features😍
