### ISSUE TITLE
[1.12.2] Unable to convert Plasmids with Anti-Plasmids.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#106]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 6
BrandonsCore-1.12.2-2.4.17.208-universal
CodeChickenLib-1.12.2-3.2.3.358-universal
Draconic-Evolution-1.12.2-2.3.24.349-universal
geneticsreborn-1.12-1.16
jei_1.12.2-4.15.0.291
RedstoneFlux-1.12-2.1.0.6-universal

-----

Note:
Draconic Evolution was added just so I have a power source to work with.

![](https://cdn.discordapp.com/attachments/377171551155650560/641048852606222394/generebornantiplasmidcraftbroken.PNG)

Top:
'geneticsreborn-1.12-1.16'
Unable to convert a completed plasmid with an Anti-Plasmid. Nothing appears in the output.

Bottom:
'geneticsreborn-1.12-1.14'
Can convert a completed plasmid with an Anti-Plasmid. The converted plasmid appears in the output.

Now... I wonder of any other recipes are bug'd since there's mutations & such although I still need to learn more about that.

**Comment by clubpetey** [comment]
Fixed in next release.

**Comment by clubpetey** [comment]
Also, mutations are all done via the brewing stand or incubator.  The recipe bugs are due to my conversion from the old forge recipes to the new JSON-specified recipes. Point is, mutations wont affect recipes.

**Comment by SonicX8000** [comment]
Ah, alright. Just wanted to check due to the past bugs I ran into.
