### ISSUE TITLE
[1.12.2] Cybernetic Gene appears to be unobtainable in survival.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#108]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 8
BrandonsCore-1.12.2-2.4.17.208-universal
CodeChickenLib-1.12.2-3.2.3.358-universal
Draconic-Evolution-1.12.2-2.3.24.349-universal
geneticsreborn-1.12-1.17
GrimoireOfGaia3-1.12.2-1.6.9.3
jei_1.12.2-4.15.0.291
RedstoneFlux-1.12-2.1.0.6-universal

-----

Gotten about 78 Organic Matter from a 'cyberware:cyberzombie' and went to decode them and only got 78 Basic.

Just in case maybe modded genes are affected, I've installed Grimoire Of Gaia 3 and took 20 Samples off a 'grimoireofgaia:dryad' and decoded them and gotten 7 Basic & 13 Photosynthesis.

Not sure if adding it via commands works as I've ran into a bug which I'll post an issue in a bit. Have to get a gif of it first.

**Comment by clubpetey** [comment]
The cyberzombie isn't registering correctly.  I'll fix it in the next release, but before that you can add the entity to the JSON config to grant the gene.  The entity name should be "EntityCyberZombie"

**Comment by SonicX8000** [comment]
Unless I did something wrong... it crashes upon load.

Crash Report:
https://pastebin.com/7CDzPFJy

This is what's written in the JSON.
```
{
  "EntityCyberZombie": [
    "cybernetic"
  ]
}

```

Was I suppose to leave the test stuff in there?

**Comment by clubpetey** [comment]
Your format is correct, the loading code has a bug, I will look at it tonight.

**Comment by SonicX8000** [comment]
Just going to mention that I added the cybernetic gene via commands and it seems it doesn't fully work correctly.

In the configs... tolerance boost is at 25 for Genetic's Reborn. Cyberware's aka Robotic Parts is set at 100 Tolerance with the low tolerance threshold at 25.

The Robo Surgeon's GUI doesn't see that I have the gene so it still says I have 100 Tolerance. If I go below the thershold despite having a supposed boost... I start taking damage due to low tolerance however this fixes itself if I inject myself with the gene again... until I open the Robo Surgeon in which I start taking damage again.

If I remove the gene while at... say 26/100 Tolerance... I start taking damage due to low tolerance. I assume the value now is 1/75 due to the removed gene although I can't say for sure since viewing the GUI will 'fix' the value back to 26/100. Now... if you do this at... say 24/100, I assume the value is set at -1/75 which... because I have no tolerance now... I instantly die.

Might it be possible that cyberware doesn't see the gene as a tolerance boost? It would've shown me having 125 tolerance if it sees me having the gene only... it kinda does.

*EDIT*
A correction on the 'instant-kill' part.

**Comment by clubpetey** [comment]
When you add the gene I add 25 points.  It looks like the roboDoc is resetting you to 100.  Then you remove the gene and get dropped to 75.  I'm going to open a bug with Robotic Parts.
