### ISSUE TITLE
Another small bug

### ISSUE THREAD

**Issue by mcpecommander** [TheUnderTaker11/GeneticsReborn#11]
when you remove all of the gene using the cheating tool in creative , you lose the ability to fly.
I mean it is creative and you can not fly haha

**Comment by TheUnderTaker11** [comment]
... I feel like you said this before and I forgot. Sorry about that, it's just that creative flight only applies the flight ability once when you go into it, so unlike other modded items where you will still have flight, creative flight works differently. My bad if you have said this before, writing it down now.

**Comment by TheUnderTaker11** [comment]
Fixed for update 0.15
