### ISSUE TITLE
DNA Extractor Insertion

### ISSUE THREAD

**Issue by Tim2162286** [TheUnderTaker11/GeneticsReborn#113]
When i tried to automate the DNA extractor, items were getting inserted into the right output slot instead of the left slot.
![image](https://user-images.githubusercontent.com/15058004/68538915-48587f80-0339-11ea-8e1c-b1d8fb1ef73e.png)
The cells were inserted through a hopper in the top of the block.

**Comment by clubpetey** [comment]
Verified this is working correctly on v1.20, if you are using a previous version, please update to the latest.
