### ISSUE TITLE
Infinite More Hearts gene use

### ISSUE THREAD

**Issue by PowerPunch360** [TheUnderTaker11/GeneticsReborn#115]
![2019-11-12_05 25 19](https://user-images.githubusercontent.com/57645613/68671637-f9fbda00-050c-11ea-88a4-86c913860401.png)

You can give yourself the More Hearts gene infinite times, even by just re-injecting your blood. Issue tested on 1.17 and 1.20.

**Comment by clubpetey** [comment]
fixed in v1.21
