### ISSUE TITLE
Can't get mutated genes

### ISSUE THREAD

**Issue by PowerPunch360** [TheUnderTaker11/GeneticsReborn#117]
![2019-11-12_LI](https://user-images.githubusercontent.com/57645613/68674606-68439b00-0513-11ea-9738-2ecacc2c939f.jpg)

I went through the process and was able to manufacture mutated cells. Cells can't be put into the DNA Decrypter like the Wiki says, so I assumed it was a typo and I put them in the DNA Extractor instead. I only get Basic Genes or the appropriate specialized ones, but never get mutated genes. I'm not sure what "unless noted" means in the Wiki. Tested on 1.17 (later versions are bugged).

**Comment by clubpetey** [comment]
Fixed in release 1.21, also changed the wiki text to be a bit more clear.
