### ISSUE TITLE
flight gene

### ISSUE THREAD

**Issue by tjd46** [TheUnderTaker11/GeneticsReborn#118]
I'm having issues applying flight with either bat or parrot mutations I get the whole thing ready and inject myself it does the blindness and health damage but doesn't give fly gene. other than that I have tried to get the gene from wither but nothing but basic and wither proof are coming out I even when into a creative world and did this https://i.imgur.com/SmyQVor.png . I tested this out in both ver 1.20 and 1.21

**Comment by tjd46** [comment]
went back as to 1.14 and it started dropping again from wither.

**Comment by clubpetey** [comment]
Wiki Page was incorrect, it has been updated.  Flight now only drops from the Ender Dragon naturally.  If you want to acquire flight by mutation, it requires that you have either the JUMP BOOST or TELEPORTER gene already in your body.
