### ISSUE TITLE
Plasma Injector

### ISSUE THREAD

**Issue by IDK2019** [TheUnderTaker11/GeneticsReborn#119]
Every time I go to put in the glass syringe it crashes my game telling me Error: java.lang.NullPointerException: Updating screen events. Its only for the plasma injector.

**Comment by clubpetey** [comment]
This is happening because you are putting an empty glass syringe in the Injector.  That is not allowed, I will correct the game crash in the next release, but in the mean time, only full syringes with pure blood should be placed in the Injector.
