### ISSUE TITLE
Potion stacking

### ISSUE THREAD

**Issue by theProdWorm** [TheUnderTaker11/GeneticsReborn#122]
I've been up all night, all day trying to find a way to remove the potion stacking feature from the mod, but I am completely incapabable both of finding a way to edit .jar/.class files, and of reading the java language as well as the function names in the code. At last, i had enough, and so I thought I would ask a proffessional instead. So, I'm hoping that someone is smarter than me and can resolve this issue, as this is a very frustrating feature because it removes all ability to automate the process of potion making.

So, to be very clear, this mod adds the feature of potions, as well as water bottles, to be stackable. I want potions, as well as water bottles, to only be able to stack up to ONE, so that pipes or hoppers will not insert more than ONE potion into the incubator at once, thereby destroying the brewing process. Again, no potion stacking, this ruins automated brewing.

Other than the mod destroying itself, in a way, it's a very nice mod. I love being able to manipulate my genes and adding things like eat (gr)ass or speed, but... we could use a config file for things such as this.

Versions:
Minecraft 1.12.2,
Genetics Reborn v1.15 & Genetics Reborn v1.21

**Comment by TheUnderTaker11** [comment]
If you had looked in the config you would have seen there is a "Stack Potions" section, which you can simply set to false.
That should fix your problem!

Edit: And feel free to re-open (or if you can't comment for me to re-open) if it does not fix your problem.

**Comment by theProdWorm** [comment]
Problem is... there is no config file. And I don't know how or if I can reopen this issue.

**Comment by TheUnderTaker11** [comment]
@theProdWorm There is a config file. I just tested myself, and this mod will make it's own folder in your directories config folder, as shown here               
![image](https://user-images.githubusercontent.com/16872377/71846327-eb0a5180-308f-11ea-85f0-b45c502f2274.png)           

If you don't see it, you must be looking in the incorrect directory. I suggest using the launcher itself (whichever one you happen to be using) to get to the directory of your modpack.            
You could easily be looking for it in %appdata% when it's a Curse pack that stores pack directories in completely different places.

If you are Linux or MacOS, it might be worth reopening, but like I said I just tested myself five minutes ago and can confirm it works.

**Comment by theProdWorm** [comment]
There, found it at last. Thank you!
I was looking from the "mod options" tab in Minecraft, and also from the mods folder in %appdata%. I did find it in %appdata%, but in the folder that quite clearly is named "config", which I had completely overlooked. Might wanna consider making it visible from inside of Minecraft, because that's much easier to find. Just saying.

Anyway, thanks for prompting me to find the config folder!

**Comment by theProdWorm** [comment]
Pretty sure I found another bug, which I really should've realized sooner. (Edit: reason for this is because I build the entire automation system before I tested if the incubator can output out the bottom) 
I'm trying to make a setup to automate the brewing of flight cells, and the first problem was the main issue, but now I found another one. The advanced incubator does not output from any side. The output method I'm using is transfer nodes from extra utilities 2, which works just fine on all of the other machines in genetics reborn, but only on the advanced incubator does it not work.
I'm hoping you can resolve this quite quickly, because I'm really into this and it's not that nice when I have to keep it on hold just because there is a small bug that stops me from automating an extremely slow process...
I know I sound like "f u make this work" but I really like the mod and would like to continue using it, which I am not able to in an efficient way if automation does not work.

**Comment by clubpetey** [comment]
The Adv incubator switches sides from input to output depending on where in the process it is... What is supposed to happen is the sides are input until the brewing process starts, then they are "nothing", when the brewing process completes, the sides will be outputs for 20 ticks, then switch back to input. 

The original purpose was to stop the insertion of items during brewing reset the brewing timer and to stop pipes with auto-pull extracting the contents before they are brewed.  However, some pipe systems seem to have trouble with sides that change modes.  It looks like the check the mode once when connected and never again.

There already is a ticket to look at the stacking issue.  I will look at both this week and try to come up with a better solution.

**Comment by theProdWorm** [comment]
Not that I have any say in this, but I'm thinking:
* Input on left and right sides
* Output out the bottom
* Ingredient from the top
* Chorus fruit from the back and front
* Power from any side

A solid fix to the problem with pipes that pull out items would be to simply switch off the IO on all sides during the brewing process , and when done turning on output for the bottom side, and then when all potion slots are empty, the IO will switch on for all sides. Might put a config for the IO so that users can edit the IO for themselves (lets say they want output from all sides).

My automation system would work flawlessly with these IO settings, just saying ;)

Side note: if you try inserting an item from the front via a pipe or hopper it will be inserted into the chorus fruit slot even if it isn't a chorus fruit.
