### ISSUE TITLE
Stacked potions don't work in this mod's Incubator.

### ISSUE THREAD

**Issue by TheUnderTaker11** [TheUnderTaker11/GeneticsReborn#123]
Title. Made this as a more specific bug report compared to the other one I closed. While you did make it a config value, stacked potions won't brew in our machine.
Either make it brew a stack at once, or only accept one bottle in each slot at a time, but according to #122 , it does not work at all while stacked in the machine.

Version he gave
Minecraft 1.12.2,
Genetics Reborn v1.15 & Genetics Reborn v1.21

**Comment by clubpetey** [comment]
Adding a note to look at mods with pipes and fix how they insert/extract the components.

**Comment by clubpetey** [comment]
Input slots have been configured to accept only one item at a time.  Input/Output Capabilities have been improved to work with pipes better.
