### ISSUE TITLE
[Suggestion] Modded mob compatibility?

### ISSUE THREAD

**Issue by Keetarin** [TheUnderTaker11/GeneticsReborn#125]
It would be nice if I could add modded mobs as a source for genes, like adding the animals from animania acting like their vanilla counterparts, whether automatic or manually via config/json it would add some flexibility for modpack developers. 
Edit: GAH, I really need more sleep, the number of errors was unacceptable 
Edit 2: NVM, didn't notice that this function has already been added.

**Comment by TheUnderTaker11** [comment]
I found this pretty funny not gonna lie.

**Comment by Keetarin** [comment]
While it wasn't my intent to entertain I do admit it was funny. 
Looking back I really should have been in bed at that time.
