### ISSUE TITLE
The Wiki says you can get these Genes but ingame they are different.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#129]
Using 'geneticsreborn-1.12-1.21'

Example 1
https://github.com/TheUnderTaker11/GeneticsReborn/wiki/Resistance

Unless Zombies only give you Resistance I while Shulkers can give you Resistance II but a glance at the code only shows that you can get Resistance with a normal gene and a mutated gene of that type makes it become Resistance II.

The commands also shows RESISTANCE & RESISTANCE_2 as possible commands which gives Resistance & Resistance II.

-----

Example 2
https://github.com/TheUnderTaker11/GeneticsReborn/wiki/Regeneration

Regeneration is another oddity where it says Regen II & Regen IV however you only get Regen I & Regen II.

A look at the commands shows REGENERATION which gives Regen I & REGENERATION_4 gives you... Regen II.

Is the wiki outdated in some parts or something?

**Comment by clubpetey** [comment]
Except for bosses, mobs will give you basic genes only.  When the wiki says you can get the gene from mutations, you have to mutate the basic gene, and mix it with the right components to get the mutated gene.  So zombies/shulkers only give Resistance. 

Regeneration "4" is a bug.  Currently the regeneration are I and II, they should be II and IV.  The next release will fix this.

**Comment by SonicX8000** [comment]
Ah, alright. Unsure if other genes are like this but I see a EFFICIENCY & EFFICIENCY_4 in the command list... although after testing them I don't seem to notice any difference for the dig speed.

https://github.com/TheUnderTaker11/GeneticsReborn/wiki/Efficiency

...and the wiki says it's suppose to be Efficiency II for EFFICIENCY? Then again... wouldn't it be EFFICIENCY_2?

**Comment by clubpetey** [comment]
I checked all the 1/2 and 2/4 genes, they are (now) correct.  I agree the Efficiency IV isn't a big boost,   But it does follow the math that Minecraft uses...  In the next major release all these values will become configurable, and you will be able to change the genes boosts with the config file.
