### ISSUE TITLE
Rotating Machines with the yeta wrench from enderio destorys whatever is in the machines

### ISSUE THREAD

**Issue by pp-pp-pp-pp** [TheUnderTaker11/GeneticsReborn#13]
title

**Comment by TheUnderTaker11** [comment]
Wasn't aware my machines could even rotate at all. I'll get right on this.

**Comment by TheUnderTaker11** [comment]
Bug fixed, would you like an update with the fixed version now or would you not care to wait a few days or so before the next version comes out?

**Comment by TheUnderTaker11** [comment]
Released 0.15
