### ISSUE TITLE
question - do i need jump boost after obtaining flight from mutated bat cells

### ISSUE THREAD

**Issue by DartisXUI** [TheUnderTaker11/GeneticsReborn#131]
i used jump boost to get flight from bats, but its seriously annoying me and is affecting my ability to use flight
flight only seems to enable after the effects of the boosted jump have ceased - ie: jump up two blocks, fall one block (and if you're still holding space bar) then rise into flight.

this is messing with my head, and as i panic enough with mobs in minecraft, i dont need issues trying to get away from them as well

so now ive reached the requirements for flight (ie: jump boost), got flight, can i now use an anti plasmid to remove jump boost without loosing flight?

**Comment by DartisXUI** [comment]
so, if i remove jump boost, will i loose flight?

**Comment by clubpetey** [comment]
No, you only need jump boost to add flight, once you add it, you can remove jump boost.
