### ISSUE TITLE
Plasmid Injector doesn't accept Metal Syringe

### ISSUE THREAD

**Issue by TheUnderTaker11** [TheUnderTaker11/GeneticsReborn#132]
https://github.com/TheUnderTaker11/GeneticsReborn/blob/c41eb89f37c6d22b7d57c3d9a58fc6e3f8764150/src/main/java/com/theundertaker11/geneticsreborn/blocks/plasmidinjector/ContainerPlasmidInjector.java#L118

Simply include metal syringe as an item at this line, currently only accepts glass.

**Comment by AnkokuTenebris** [comment]
How can i implement this? i have the last version aviable in forge (nov 13, 2019) so this is not implemented as i can see (21 days ago).

**Comment by clubpetey** [comment]
This is fixed in the upcoming release, I should have the release out this weekend.
