### ISSUE TITLE
[1.12.2] Oddity with Splash Potions? & CraftTweaker script oddity with Potion Core.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#133]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 2
geneticsreborn-1.12-1.21
jei_1.12.2-4.15.0.291

-----

![](https://cdn.discordapp.com/attachments/377171551155650560/673968221761699912/GBpotionoddity.PNG)
I noticed in the JEI menu that there's another set of splash potions but without the purple glint. Hovering over them shows the same effects as the vanilla potions.

If you use these potions... which according to the data is named as 'geneticsreborn:viralpotion', they are thrown as intended but no effects are gained and the color of the potion is the same as those unknown potions.

If you add in mods that add in more potions... you'll get more of these viral potions.

-----

Mods: 4
CraftTweaker2-1.12-4.1.19
geneticsreborn-1.12-1.21
jei_1.12.2-4.15.0.291
PotionCore-1.8_for_1.12.2

Figure I mention this as well if using Potioncore. When Potion Core is added... the 'Virus Protection' name gets changed to 'Cure'. The effects appear to work alright but wonder if there's maybe a conflict going about.

If you add in CraftTweaker + Potion Core and use this script here...
https://drive.google.com/file/d/1PXeyFnGxc8EDzjl39pSFD1QX9Vj0nN0h/view?usp=sharing

...which gives recipes to the Potion Core Potions as by default they have no recipe. A strange thing occurs if used alongside Genetics Reborn where you're unable to brew any kind of Splash Potion with Gunpowder as they'll always turn into 'Cure' Splash Potions from Genetics Reborn.

**Comment by SonicX8000** [comment]
Found another Potion Name conflict if you have Resizing Potion installed, although the potions do appear to work as they should... kinda. Resizing Potion allows you to change sizes of Players & Mobs.

Mods: 8
ArtemisLib-1.12.2-v1.0.6
BrandonsCore-1.12.2-2.4.18.210-universal
CodeChickenLib-1.12.2-3.2.3.358-universal
Draconic-Evolution-1.12.2-2.3.25.351-universal
geneticsreborn-1.12-1.22
jei_1.12.2-4.15.0.291
RedstoneFlux-1.12-2.1.0.6-universal
resizingpotion-2.2

-----

Looking at the "Potion of Cell Growth - Mega Bone meal". One set of potions has 'minecraft:potion' & 'minecraft:splash_potion' while the other set has 'geneticsreborn:viralpotion'& 'geneticsreborn:grpotion'.

Using the 'minecraft:potion' version of Cell Growth... you apparently drink it and get it's effect which wears off for a splash second. The 'minecraft:splash_potion' does the same thing only this one can be thrown.

Now for the 'geneticsreborn:gfpotion' for Cell Growth... you can throw it and it bonemeals the grass allowing you grow tall grass & flowers... however the 'geneticsreborn:viralpotion' for Cell growth... does nothing when thrown.

If you install 'Resizing Potion'... the tooltip for the "Potion of Cell Growth - Mega Bone meal" gets changed to 'Potion of Resizing - Growth'. The effects are still the same, however. Another oddity is that a Lingering  Potion of the Cell Growth... called Resizing due to the conflict... gets added which when thrown... does nothing.

**Comment by clubpetey** [comment]
Ok, so it seems that potionEffect and potionType names are not mod-localized like other items/blocks.  So both GR and PotionCore have a potionType and a potionEffect called "Cure".  This was causing a lot of mess.

I've changed the name of our potionType/Effect in 1.24 to solve this problem.  But it means that anyone that has brewed cure potions will have them disappear or change to "unknown" potions after upgrading.

As for the duplicate potions without glint I cannot get rid of, but you should not be able to craft them.  Minecraft does some auto-creation of potions that I cannot stop.  It clutters the creative tab, but has no effect on the game.  As you noted, you need the GRPotion versions of potions to get the effects.
