### ISSUE TITLE
Removed Jump Boost using anti-Plasmid procedure - didnt seem to work

### ISSUE THREAD

**Issue by DartisXUI** [TheUnderTaker11/GeneticsReborn#134]
are anti-plasmids, instant, or do they take time?
i asked about removing jump boost after getting flight - it was said i could.
turns out it didnt work 

- maybe its supposed to but as its a requirement to obtain flight - flight is protecting its removal somehow? (bug)
- maybe its not supposed to work (intended)
- maybe i screwed up somewhere (but i dont know how)

either way, it hasnt worked immediately

(and yes, i searched for "Anti" in the open/closed requests and didnt find anything)
(you closed the last issue on this... i assumed i had to open another one... sorry if not)

**Comment by DartisXUI** [comment]
i have made another anti plasmid - its ready to go, but i dont want to potentially waste another until i know what happened - or how to help you find out

**Comment by DartisXUI** [comment]
so more developments on this issue:
i had been waiting to hear back on what to do now my first attempt didnt work, but after beating the ender dragon, visiting the end city and heading home again i woke up with no abilities...

the procedure wasnt standard, it went:
arrived and end, beat the dragon.
set up stargate from stargate network, travel home via it.
clear inventory
gated back to end
used ender pearl to go to end city entrance island
set up stargate there (im seeding the modpack dimensions with gates)
-i may have gated back home using the gate at this point, but i dont think so-
used ender pearl to return to the end
returned to the exit portal (can still fly at this point)
pressed esc to exit credits
woke up in bed without abilities: water breathing, mob sight, jump boost, flight & fire proof (although i didnt know it at the time, but wondered why i couldnt fly at first, then noticed i was taking fall damage, then noticed i could only jump one block)

now for the jump boost part of this issue:
went to my backup syringe, noticed it had everything on it and thought, maybe if i dont have jump boost already in my system, maybe i can remove it properly...
used my spare anti jump boost plasmid - checked the syringe still had it, dismayed i reinjected myself
i still have jump boost (after 2 attempts at getting rid of it) 
...
...
but now i no longer have flight???!?

things are getting worse for me here... 

so umm... 

**BUMP**

**Comment by clubpetey** [comment]
Some of this I can explain...

The mod isn't currently smart enough to notice that jump boost is in the syringe along with flight.  So you would need two syringes since flight relies on jump boost.  you would need to inject jump boost first then flight in two separate actions.  However I think I can fix this in the next release.

The missing all genes after the credits is strange, the genes hold through dimension transfers, but maybe the dimension transfer from the end is different some how.  I'll have to look into this.

There's a release coming out this weekend, that will correctly let you remove jump boost.

**Comment by DartisXUI** [comment]
sweet - ill be able to update then, then. as regenerations needs an update to on my server, ive been holding off so everyone playing sdoesnt have to redownload the modpack... 

but thats not something that helps here

thank you for getting back to me

**Comment by DartisXUI** [comment]
just an update on what ive tried doing - i can confirm that the anti-plasmid did not work for the other gene thats reported not working properly, ie: Mob Sight (theres a issue for that, that ive been reporting on as well).
basically with that gene working on yourself and not the other mobs i tried to remove it instead. but it did not

**Comment by clubpetey** [comment]
Fixed in next release
