### ISSUE TITLE
Add overclocker to wiki

### ISSUE THREAD

**Issue by NordicGamerFE** [TheUnderTaker11/GeneticsReborn#135]
Hey i am currently making quests for my modpack and wiki about the overlocking upgrade even tho i know what it does i love to give my users correct stats about how much the speed increase for each time one is added. sorry if its on the wiki and am just blind but i dont have unlimited time to look thru wikies

sincerely Kevin

**Comment by NordicGamerFE** [comment]
Also potions in the wiki and game seems to mix match any information on this?

sincerely Kevin

**Comment by clubpetey** [comment]
Each over-clocker will reduce the total ticks to complete a machine cycle by 39, but increase the RF cost PER TICK by 85
