### ISSUE TITLE
How to get flight gene

### ISSUE THREAD

**Issue by GAmeZStaR28** [TheUnderTaker11/GeneticsReborn#136]
I've created a mutated cell in the incubator and made an helix out of it, which was decrypted. I've encrypted it and got no flight helix. I did this 8 times and I still get no flight helix. Am I doing something wrong?

**Comment by DartisXUI** [comment]
you need to use incubator in low temp mode - click the spiral fuel symbol - then it will change brightness (if you havent done so)

next i used about 4 or 5 incubators simultaneously
1 for duplicating cells on low temp mode:

Substrate (Tier 0): Mundane Potion + Any Organic Matter
(Used to duplicate Cells (Base Potion))
i.	Substrate + any Cell = 3 of the same Cell (Brewing Stand or High Temp Incubator)
ii.	Substrate + any Cell = 18 of the same Cell (Low Temp Incubator)

the others worked on the mutated bat cells.

you will need to keep up you influx of bat cells as i only got about 3 flight genes out of 3 stacks
whether this was not intended or not - im not on hard mode, so i finished things off with "mutated" basic cells

**Comment by clubpetey** [comment]
DartisXUI description is correct.  There will be a mod-spotlight coming out soon that will provide detailed steps for creating all the advanced mutations and viral agents.
