### ISSUE TITLE
Dont understand

### ISSUE THREAD

**Issue by Arm00s** [TheUnderTaker11/GeneticsReborn#137]
Its about mutation , i did like 3-4 try , i get mutated cell then i put it in the DNA extractor etc...
and i every time obtain the basic gene , i tried this on low temp  high temps normal incubator , advanced one , and normal. i dont understand how to do to get mutated gene

**Comment by clubpetey** [comment]
There was a mis-calculation in the chance of getting a non-basic mutated gene.  It was correct in release 1.23
