### ISSUE TITLE
Dont understand viral agents

### ISSUE THREAD

**Issue by AnkokuTenebris** [TheUnderTaker11/GeneticsReborn#139]
Well, im in 1.12.2 trying to create a BVA, but even with the steps in the wiki im not able to do it.
I create the normal viral agent bottle (because i cannot move the bottle from my inventory to the incubator), and i put in the top the helix, i tried with basic ones, mutated, revelated... but nothing.
Im not sure if im doing something wrong but when, for example, i try to get a mining fatigue agent i use rabit and silverfish cells, DNA, and the result is the same, i use the helix as the wiki sais but it just dont work.
Also, another problem i have is that when i try to draw blood to a mob with the metal syringe, a message appears saying "That is disabled in the configuration", there is any way to solve it?

**Comment by AnkokuTenebris** [comment]
(Ok i solved the syringe problem)

**Comment by clubpetey** [comment]
There will be a mod-spotlight video coming out soon with a more detailed explanation, however the general steps are:

1. Create BVA
2. Create helix with gene you need 
3. Use Advanced Incubator AND a Chorus Fruit as fuel to create Viral Potion

So for Mining Fatigue, you will need a DNAHelix with the "Haste" gene.  Place 1-3 BVA in the lower slots of the Advanced Incubator, add the helix to the top slot, add a chorus fruit to the fuel slot, set the Adv. Incubator to LOW HEAT (click the yelow-ish bar), and wait about 20 min.

If you do not use low heat or the chorus fruit, you can still get a viral potion, but your chance of success is very low (< 3%).

**Comment by AnkokuTenebris** [comment]
Yeah i stand that, the problem is that it just not work, when i put any helix on the top, nothing happens, even with the fruit or the low temp mode, it just not works.
For example a speed helix from a rabbit, nothing, a strengh one from a bear, nothing.
Ah and when i try to put a syringe in the incubator, the game crashes.

**Comment by AwiZy63** [comment]
Issue Found ??

> Yeah i stand that, the problem is that it just not work, when i put any helix on the top, nothing happens, even with the fruit or the low temp mode, it just not works.
> For example a speed helix from a rabbit, nothing, a strengh one from a bear, nothing.
> Ah and when i try to put a syringe in the incubator, the game crashes.

**Comment by 7eggert** [comment]
1) Put sugar on water
2) Put organic matter on the result
3) put a gene on the result
4) put a fermented spider eye on the result
5) put a bear cell on the result
6) put the diamond (IIRC) on the result, THIS needs to be low temp and you need the fruit exactly if you've installed speed upgrades (otherwise you get worse results)
7) put the resulting cell into the extractor
8) complain about this process being badly documented

**Comment by clubpetey** [comment]
@7eggert is correct, I will work on improving the documentation.
