### ISSUE TITLE
Tooltip request

### ISSUE THREAD

**Issue by pp-pp-pp-pp** [TheUnderTaker11/GeneticsReborn#14]
The blood should have tool tips saying if there is a gene in them or not. When I made my first power, I thought I did something wrong because The blood was contaminated and I couldnt inject it. Tooltips saying "This blood has XYZ gene would be very helpful."

**Comment by TheUnderTaker11** [comment]
That would leave a massive tooltip when you have a solid 15-20 genes. I've been trying to think of a good immersive way for players to see all genes they have on them, but you woulden't be able to see directly from the syringe.
