### ISSUE TITLE
Compile current code if possible

### ISSUE THREAD

**Issue by TheUnderTaker11** [TheUnderTaker11/GeneticsReborn#141]
I tried compiling what was in the github repository, but not sure if there is some partially finished stuff, or some other problem, but it just caused even more bugs.       

The main reason to do this is for the metal syringe fix, some people really like it and currently, it can't be used at all without that fix.

**Comment by clubpetey** [comment]
I'll compile the current base this weekend, I am out of town for the next 3 days.  I've been holding off trying to fix the interactions with the Incubator and pipes, which is causing me some strife.  However, when you say "bugs" are you saying during compile? or in the mod?  Are there specific things you want me to test before release.

**Comment by TheUnderTaker11** [comment]
I just compiled it and put it on the discord and they said they were
getting even more problems.
Which happens, there is plenty of times compiling a mods source code by
someone else doesn't work for me for whatever reason.

**Comment by clubpetey** [comment]
Compiled and pushed.
