### ISSUE TITLE
Climb Walls no longer works after a game restart

### ISSUE THREAD

**Issue by xReckless** [TheUnderTaker11/GeneticsReborn#142]
Forge: 14.23.5.2838 / 14.23.5.2847 (Tested on both)
Mods: Only GeneticsReborn

After obtaining the Climb Walls gene it works as intended until you completely restart your game then it does not work at all until you remove the gene and re add it

**Comment by clubpetey** [comment]
I have tested this by repeated restarting my game and each time the CLIMB_WALLS gene is active upon login.  Do you have any other mods installed?  Maybe one of them is affecting wall climbing.

**Comment by xReckless** [comment]
Only using genetics reborn heres a video of the bug
[Video](https://youtu.be/oVDHXGqn0vw)
Tested on both 1.14 and 1.22 of the mod aswell as the forge versions listed in the original post

**Comment by clubpetey** [comment]
I was able to re-produce this.  Fixed in 1.24
