### ISSUE TITLE
Bear gives resistence mutation instead of claws

### ISSUE THREAD

**Issue by 7eggert** [TheUnderTaker11/GeneticsReborn#143]
https://github.com/TheUnderTaker11/GeneticsReborn/wiki/Mutations
"PCM(Bear/Llama cell) + Diamond = 50% Claws II vs Claws I"

https://github.com/TheUnderTaker11/GeneticsReborn/blob/1.12.2/src/main/java/com/theundertaker11/geneticsreborn/potions/GRPotions.java
```
		BrewingRecipeRegistry.addRecipe(new ComplexBrew(MUTATION_POTION, Items.EMERALD, "EntityPolarBear",  EnumGenes.RESISTANCE, 50));
		BrewingRecipeRegistry.addRecipe(new ComplexBrew(MUTATION_POTION, Items.EMERALD, "EntityLlama",  EnumGenes.STRENGTH, 50));```

Similar problem for strength

**Comment by clubpetey** [comment]
Fixed in next release
