### ISSUE TITLE
MORE_HEARTS gene only gets removed upon death even if 'keep genes upon death' is set to true. Also... MORE_HEARTS_2 doesn't seem to apply it's extra health.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#146]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 2
geneticsreborn-1.12-1.22
jei_1.12.2-4.15.0.291

-----

If you add the 'MORE_HEARTS' gene whether it be legit or by commands... it works as intended... however if you then remove the 'MORE_HEARTS' gene... you still keep the 20 extra health from the MORE_HEARTS gene.

If you add the MORE_HEARTS_2 gene while having the MORE_HEARTS gene... you won't get the extra +20 health which I assume with both of those genes I would've had 60 health but I remain at 40 health.

Another issue to report is that despite the 'keep genes upon death' being set to true in the config file... you lose any extra health upon death. By any chance this bug might've occur due to the fix with stacking the MORE_HEARTS gene?

*EDIT*
I went back to 'geneticsreborn-1.12-1.21' and the MORE_HEARTS gene can be removed normally... howeverthe MORE_HEARTS_2 gene still appears to be bug'd where it won't apply it's extra health.

**Comment by clubpetey** [comment]
Fixed in next release, MORE_HEARTS(_2) is adding/removing correctly, even upon death.
