### ISSUE TITLE
Game crashes if you put in a 'Mutated Gene' Helix inside the Plasmid Infuser.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#147]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 2
geneticsreborn-1.12-1.22
jei_1.12.2-4.15.0.291

Report:
*Cilent* - https://pastebin.com/tqYVBBMi
*Server* - https://pastebin.com/GnZpSVte

-----

Was trying to get the LUCK Gene which is gotten from making a mutating Rabbit Cell. When I got the DNA Helix from a Mutated LUCK Cell it said 'Mutated Gene' so I wasn't sure if that was the correct gene.

I go to the Plasmid Infuser, put in a Plasmid with no genes set and then put in the DNA Helix with the 'Mutated Gene' and then... as soon as I placed the DNA Helix inside the Infuser... the game crashed.

**Comment by Teibidh** [comment]
Or unknown genes.

**Comment by clubpetey** [comment]
After being brewed, a LUCK cell will have the words "Mutation: LUCK" in it's tool tip.  If you see "Mutation: Basic Gene" then that is not a luck cell, that is the mutated equivalent to the "Basic Gene"

After you send the cell through the DNAextractor and DNAdecrypter, the helix tooltip will say either "Gene Type: Mutated Gene" or "Gene Type: Luck".  Again, the first helix is the mutated basic gene, the second is the luck gene you are looking for

As long as you are not in hard-mode, the mutated basic gene can be used to fill a plasmid, but only after the plasmid has been "locked" to a gene using a non-basic gene.  I have fix the plasmid infuser to not crash if a basic gene is inserted with a blank plasmid, but you still must "lock" the plasmid before using basic genes on it.
