### ISSUE TITLE
Teleportation stopped working

### ISSUE THREAD

**Issue by MrYpsilon** [TheUnderTaker11/GeneticsReborn#148]
Can't teleport anymore after gaining Flight and Dragon Breath and changing the keybinding for latter. 
Changing it back didn't help, neither did reinjecting my blood, reconnecting to the server or restarting the game.

**Comment by clubpetey** [comment]
What version of the mod are your using?

**Comment by 7eggert** [comment]
I'm using geneticsreborn-1.12-1.22.jar and this happens after playing for a while. When I start, I need to inject a syringe to re-activate spider powers, and for a while the keys for teleport and breathing will work. Then teleport stops, then dragon breath.

I needed to change the keybindings to tab (teleport) and the key above (breath)

**Comment by MrYpsilon** [comment]
> What version of the mod are your using?

The one for 1.12.2
Began working again after restarting the server.
I found another problem though, where it's not possible to use Teleportation when someone else is already teleporting (not sure if that is somehow caused by the server).
Also I randomly got invisibility and can't get rid of it (Anti-Plasmid doesn't work)

**Comment by clubpetey** [comment]
Fixed in 1.24

**Comment by clubpetey** [comment]
Couple notes on Teleport.
1. It does have a short cooldown (2-4 seconds)
2. It can and WILL teleport into walls, use only in open areas
