### ISSUE TITLE
Suggestion: No wall climbing while sneaking / hotkey

### ISSUE THREAD

**Issue by 7eggert** [TheUnderTaker11/GeneticsReborn#150]
a) While sneaking, wall crawling should not happen (not upwards).
b) Wall climbing needs a way to be disabled temporarily.

**Comment by clubpetey** [comment]
Good idea, wall climb is now disabled when sneaking.
Also, activating the anti-field orb will disable wall climbing.

**Comment by 7eggert** [comment]
The orb works the wrong way around. Also I'd like to suggest a specific orb (craft with  a string) to selectively only disable spider power.

**Comment by clubpetey** [comment]
The orb blocks walk climbing when "shimering", is your's not doing that?

Also, to the idea of a specific orb.  There's a bigger re-write coming of the mod that will let you do that.

**Comment by 7eggert** [comment]
It blocks wall climbing when NOT blocking item/XP magnet. I assume it should behave the same for all uses.

**Comment by clubpetey** [comment]
Actually, the item/XP magnets were wrong... they checked only if the anti-field existed in inventory, not that it was "on".  This has been fixed in 1.24
