### ISSUE TITLE
Infinity gene weird behavior

### ISSUE THREAD

**Issue by clubpetey** [TheUnderTaker11/GeneticsReborn#156]
With Infinity Gene: 
Shooting a bow will cause it to fire two arrows. Additionally, upon reloading a save, arrows fired with the infinity gene will have a blue potion particle effect attached to them as well as the second fired arrow disappearing.

**Comment by clubpetey** [comment]
The Infinity gene lets you fire arrows with none in your inventory, however if you have arrows in your inventory, it will consume one. This was done on purpose, so that if you have "special-tipped" arrows (fire, slowness, etc.) they will fire and be consumed first, then when you run out, you can keep firing standard arrows forever.

I cannot replicate the blue particles, unless you have "special" arrows in inventory.  The arrows fired will have the particles from the special-tips.

**Comment by DartisXUI** [comment]
as far as infinity goes - is it supposed to work with any modded bows that fire vanilla arrows (such as Draconic Evolution - i can confirm it does work) or is this a bug?

**Comment by clubpetey** [comment]
Right now, yes, that's intended.  If the consensus is that it's too OP, I may change it to affect only the standard Minecraft bow.

**Comment by DartisXUI** [comment]
im happy with it working with other mods like drac.evo - for the record

**Comment by DartisXUI** [comment]
my drac.evo bow no longer works with infinity or my gene broke when you fixed some other bugs in the 1.24/1.25 updates...
is it removed from other mods now? or should i keep trying to fix this?
