### ISSUE TITLE
1.23 Mutation Update - Advanced Incubators Work Instantly

### ISSUE THREAD

**Issue by DartisXUI** [TheUnderTaker11/GeneticsReborn#157]
High Temp Mode takes less than a second
Low Temp Mode takes about 1.5 seconds

Is this intended?

EDIT: i havent changed the configs to allow this

**Comment by clubpetey** [comment]
No, that is not intended, I added that code in to test, and forgot to remove it. :/

**Comment by DartisXUI** [comment]
woohoo!!!
everyone clone your infinite cells!!! XD

**Comment by clubpetey** [comment]
Good thing 1.24 is coming out in a few hours.

**Comment by DartisXUI** [comment]
side note:
my pink level hearts have disappeared along with my invisibility & self mob sight
my hearts are back to orange
(red, orange, yellow, green, blue, light blue, pink)
whatever changes you made fixed these few issues together

**Comment by clubpetey** [comment]
The sad thing, is I even made a note to remove that line before publish, and then forgot to check my pre-publish notes.

**Comment by clubpetey** [comment]
Fixed in 1.24
