### ISSUE TITLE
1.23 cannot complete invisibility gene with bat basic genes - hard mode: false

### ISSUE THREAD

**Issue by DartisXUI** [TheUnderTaker11/GeneticsReborn#159]
so even thought my flight gene was a mutation and i could complete it with basic genes from bats, it doesnt seem to work for invisibility - probably because bats arent invisible just thinking...

is there a type of basic cell to complete the 50 points required, or will i have to go the "hard mode" route and use only invisible genes?

**Comment by clubpetey** [comment]
There is a "Mutated Basic Gene" that can be used to add one point to the plasmid vs. two.  Create a potion of cell mutation with any left-over cell and then combine with Sugar.  75% chance to get the mutated basic gene.

**Comment by DartisXUI** [comment]
i never understood the sugar thing (and the game crashed last time i tried)

more specifically i didnt under stand the wiki on that matter - it was written with some terms that switched around that made it hard for me to decode...

will give this a try - thanks!
