### ISSUE TITLE
respawn crash

### ISSUE THREAD

**Issue by CyberFeast2K** [TheUnderTaker11/GeneticsReborn#163]
I died then I clicked the respawn button then I crashed here a link to the crashhttps://paste.dimdev.org/katebetuzo.mccrash and I was using version 
geneticsreborn-1.12-1.24.jar

**Comment by clubpetey** [comment]
fixed in 1.25

**Comment by CyberFeast2K** [comment]
ok ty

**Comment by 7eggert** [comment]
Q: Will this also fix issues while RFTools-teleporting to other dimensions?

**Comment by 7eggert** [comment]
A: Yes, but the spider gene is inactive after a restart.
