### ISSUE TITLE
Jump Boost - not an issue but an interesting mod interaction with Heroes Expansion (LuCraft)

### ISSUE THREAD

**Issue by DartisXUI** [TheUnderTaker11/GeneticsReborn#165]
While i have been trying to get rid of jump boost for a while now, i have since found a Mjolnir lying on the ground in a crater like Heroes Expansion Generates.
The powers of Thor gives you several abilites - not just lightning powers - like sturdy lungs for holding breath, extra strength, fall damage resistance... and jump boost to jump 2 blocks high

i would just like to inform you that possessing mjolnir and having gen re's jump boost *accumulates* the boosted jump - i can now jump 4 blocks high...

dont think this is a bug, just thought it was interesting

**Comment by clubpetey** [comment]
Interesting to note, but nothing I can really do to prevent this.  I could block the gene all together if LuCraft is installed, but GR is a very similar mod (in concept) to LuCraft/Heroes  Anyone using both is going to be super-OP anyway.
