### ISSUE TITLE
1.25 - advanced incubators cannot process

### ISSUE THREAD

**Issue by DartisXUI** [TheUnderTaker11/GeneticsReborn#166]
using either high or low temp modes my advanced incubators will not actually process any potion (tested with mundane, substrate, growth, mutation and viral - i obtained these potions to test with by using the brewing stand)

i expect this came about from the instant complete code for testing, but i didnt download 1.24 to know for sure

note: also, before i could shift click each separate bottle/potion into the incubators, but now they only shift click into the first slot and that wont let the incubators work

note 2: also since that last thing showed up, i cannot use the secondary input for chorus fruit - it just shows whatever is in the potion slots - so if i understand the benifits/detrimits of high temp (fast) incubators requiring chorus fruit to neutralise the detrimits, i cant do this...

appreciate it if someone could tell me if ive done something wrong...

**Comment by HCCyberCraft77** [comment]
Me too ! What a Buggy mod.
I tried to put a blood syringe in it and my game crashed !, because i don't know how to make mutation in those incubators.lol  :)

**Comment by DartisXUI** [comment]
is there a time frame for an update to this issue?
i was just waiting on my strength i & ii genes to face the Chaos Guardian was all, and have run out of things to do while i wait

if youre busy or something so be it, i dont mind waiting, i will just face the chaos guardian early is all...

**Comment by HCCyberCraft77** [comment]
I give myself the Dragon's Health gene, so i can't take any damage. I crafted some hearts and i enchanted them with unbreaking III in an anvil.

**Comment by DartisXUI** [comment]
not sure i follow you on this thread, but i did not know those crystals could be enchanted - how much durability do they get after that?

**Comment by HCCyberCraft77** [comment]
It stays the same but they don't take damages everytimes you get attacked by mobs or players.

**Comment by DartisXUI** [comment]
Nice! Unbreaking III? I'll have to get an enchanting book from advanced enchaments mod

**Comment by 7eggert** [comment]
Unbreaking III is the vanilla maximum.

**Comment by HCCyberCraft77** [comment]
Yep !

**Comment by DartisXUI** [comment]
on the side point of the unbreaking iii on dragon health crystals, i now have 9 setup...
thanks for the tip!

just hope that the incubators start working again soon though...

**Comment by DartisXUI** [comment]
ignore my last post - just remembered about advanced combat i had in the pack - my 9 Dragon Health Crystals now have Unbreaking VI !!!

**Comment by DartisXUI** [comment]
update to the enchanting of dragon health crystals - if you use ender io's "tank" to 'eat' the actually additions' "solidified experience", you can then use it to mend the crystals if you add mending onto them as well... neat!

note: i also just found out that you only need the crystals in your inventory rather than holding them in order for them to work!

**Comment by clubpetey** [comment]
Fixed in 1.26 - Shame on me.
