### ISSUE TITLE
The Spider-cannot-climb-bug was re-introduced

### ISSUE THREAD

**Issue by 7eggert** [TheUnderTaker11/GeneticsReborn#167]
(I don't know weather the other comments reached you)

The check for the spider gene did re-introduce the bug. I commented on the patch.

**Comment by clubpetey** [comment]
Sorry, which bug is this?

**Comment by 7eggert** [comment]
#142 (fixes 1.24), re-intoduced by #163 (1.25).
Edit: I cannot reproduce the error right now. Maybe it was still in the safegame from the old version before the upgrade.

**Comment by 7eggert** [comment]
I think this can be closed since it didn't happen again.
