### ISSUE TITLE
v.1.25 - How to make Mutations ? There is no crafting or brewing recipe for genetics reborn's potions.

### ISSUE THREAD

**Issue by HCCyberCraft77** [TheUnderTaker11/GeneticsReborn#168]
I used "JEI" mod  to find how to make potions on Genetics Reborn for mutations but their is no recipe for them. 
And i don't know how to do make it.

Please help me !

V1.25

**Comment by clubpetey** [comment]
Potions are a recent addition, there is information in the wiki on how to make them.  Look [here](https://github.com/TheUnderTaker11/GeneticsReborn/wiki/Mutations).  The section on Viral Agents needs some work, I'm doing some testing with that this weekend, so I'll have updated documentation on Monday.

**Comment by HCCyberCraft77** [comment]
Thanks
