### ISSUE TITLE
I can't use Dragon breath. Genetics Reborn 1.25

### ISSUE THREAD

**Issue by HCCyberCraft77** [TheUnderTaker11/GeneticsReborn#169]
i have the Dragon breath gene but when i'm pressing H, nothing is happening.

**Comment by DartisXUI** [comment]
same, this happened since 1.22 for me. i just figured i was doing something wrong - like shoot fireballs requires blaze rod...

**Comment by HCCyberCraft77** [comment]
Me too. And i tried using End Rod but still didn't work

**Comment by DartisXUI** [comment]
others have said it works, so i just guessed something wasnt documented, and i missed it in testing...

**Comment by 7eggert** [comment]
Did you check for key conflicts in the options?

**Comment by HCCyberCraft77** [comment]
Yes and i changed it to another key but it  still didn't work.
Have you tried it in your world in version 1.25 ?

**Comment by DartisXUI** [comment]
I too checked key conflicts - was my first stop. There were none, but I changed it anyway and still didn't work either

**Comment by 7eggert** [comment]
I remembered having used it, but obviously I didn't after upgrading, it does not work even after a fresh injection.

**Comment by clubpetey** [comment]
Fixed in 1.26,  also reset cooldown to 5 seconds.
