### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Nexusdog** [TheUnderTaker11/GeneticsReborn#17]
Are you familiar with the Darwin mod which came out for 1.6.4 but now appears abandoned? Was a really interesting idea and would fit perfectly with your mod if possible - thoughts?

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1443260-darwin

**Comment by TheUnderTaker11** [comment]
I feel like this only loosely relates to the theme of my mod, and not to mention how much work a project like this would be. If I added this it would just be like jamming in random features, and I don't want to do that. This would need to be a mod in itself.

**Comment by Nexusdog** [comment]
Okay, thanks for the reply anyway - and great work with the mod btw
