### ISSUE TITLE
[1.12.2] Zombie Pigmen get angry at you for doing absolutely nothing.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#170]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 2
geneticsreborn-1.12-1.25
jei_1.12.2-4.15.0.291

=====

Zombie Pigmen normally by default aren't aggressive unless you attack them, in which they will get quite angry with you and try to slay you. However...

...for some odd reason if you have Genetics Reborn installed, they will always be angry at you even if you do absolutely nothing. Doing some exploring... I found out there's a SCARE_ZOMBIES gene which prevents Zombies & Zombie Pigmen from being angry at you unless you attack them. Could this be a side effect for not having the gene? If so... should exclude Zombie Pigmen from it since they aren't normally angry at you by default.

**Comment by DartisXUI** [comment]
havent found this myself on my server, either both without and with the scare zombies gene (1.22-1.25). however, just recently, my server friend, mentioned when he went to the nether he found the pigmen very hostile... so.. maybe there's something here?

EDIT: clarified my post

**Comment by 7eggert** [comment]
If one pigman is hostile, it will attack and you'll fight back.
If you fight back, it will squeek and all pigmen nearby will become hostile.

If there are too many pigmen, the only solution is to remove all pigmen (go to peaceful and back once). (I made large floors once in order to avoid ghasts, a lot of pigmen spawned, ...)

**Comment by SonicX8000** [comment]
I've started a new world with only those mods added and spawned them in with either commands & or spawn eggs.

Without Genetics Reborn installed... they don't attack you upon spawning or seeing you, since you didn't annoy them first.

With Genetics Reborn installed... they will attack you the moment they spawn or see you and will never lose aggro no matter what... unless you have the SCARE_ZOMBIES gene or they can't see you, then they won't attack you.

**Comment by 7eggert** [comment]
I forgot that I'm invisible by another mod. When I turn it of, they don't like my face.

**Comment by clubpetey** [comment]
I THINK I fixed this in 1.26, might need some more thorough testing. Let me know how it goes after you update.
