### ISSUE TITLE
Overclocker upgrades can get erased if used incorrectly

### ISSUE THREAD

**Issue by ronyala** [TheUnderTaker11/GeneticsReborn#173]
Mod version: 1.25

Most machines can accept up to 5 upgrades, while the Coal Generator can only accept 1.
When breaking a machine, the upgrades always pop out as a single stack regardless of the amount of upgrades installed and despite the fact that they're a non-stackable item - and when clicking a Coal Generator with the stacked upgrades, all of them are taken instead of just one, even after breaking the generator only one is returned - all of them except one are erased.

**Comment by clubpetey** [comment]
Fixed in 1.26. only one OC is now taken, and popping the OC back out will not ruin your inventory.
