### ISSUE TITLE
[SUGGESTION] 1.25 - General polish to overclocker upgrades

### ISSUE THREAD

**Issue by ronyala** [TheUnderTaker11/GeneticsReborn#174]
* The Coal Generator doen't show the amount of upgrades currently installed in it.
* The Coal Generator, unlike other machines, doen't show a message when trying to add an upgrade and it's upgrades are already at max, and instead just opens it's interface.
* Maybe instead of the above, replace the upgrades being installed via right-click, and taken out via breaking the machine, with upgrade slots in the machine's interface, where you can take and put in upgrades as you wish (Like with the Generator having one slot, the Infuser having 5 slots etc...).

These are just things I thought might make a better experience when handling upgrades, not anything particularly important.

**Comment by 7eggert** [comment]
¢¢ the upgrades should be stackable, then one slot will suffice.

**Comment by clubpetey** [comment]
Updated in 1.26. Coal generator now shows overclocker count (max 1) and will provide message if you try to add more.  The right-click in/out for the overclockers has been there since the beginning, so I'm not going to change the way that works until the next major release.
