### ISSUE TITLE
[1.12.2] Some other bugs I've encountered.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#176]
Another quote from the discord but moving it over to issues.

> 3 Bugs to report.
> 
> 1. The Brewing Stand or Incubator won't accept BVA Bottle of Viral Agents, meaning that you can't finish the steps with creating the "The Cure" aka Virus Protection potion. Even if you leave those potions in there after following the steps it won't take the EMERALD_HEART Helix.
> 
> 2. The Brewing Stand & Incubator refuses to take Potions if they're stacked. While I'm aware that you have to do one at a time in the three slots, even if you right-click to place only one potion it still won't accept it. It will only take them if the stack is only one potion.
> 
> 3. There's still a conflict with the craft tweaker script which adds in brewing recipes for Potion Core Potions. If this script is used while Genetics Reborn is installed all brewing recipes that uses 'gunpowder' will always result in "The Cure" Splash Potion aka Virus Protection.
> 
> Now... I took a look at the source on github just to see something and within the "GRPotions.java" there's this line here...
> 
>         BrewingRecipeRegistry.addRecipe(PotionUtils.addPotionToItemStack(new ItemStack(Items.POTIONITEM), CURE_POTION), 
>                 new ItemStack(Items.GUNPOWDER, 1),
>                 PotionUtils.addPotionToItemStack(new ItemStack(Items.SPLASH_POTION), CURE_POTION));
> 
> ...I'm guessing this line is what allows you to brew splash potions of "The Cure". Just for a test... I removed only that line, saved & did a gradlew build which successfully created the jar file, and loaded it in a test world to check if the conflict still occurs with the script.
> 
> Now, due to 'Bug 1' I can't normally brew "The Cure" potion so I spawned it in with commands and took a "The Cure" potion & some gunpowder. I was able to brew a Splash Potion of "The Cure" without trouble. I then tried other potions from Vanilla & Potion Core like Revival, Instant Damage, Launching, Mundane, etc to see if the conflict occurs and I was able to brew those into splash potions without them converting into "The Cure" potions.
> 
> Now I dunno if anything else broke due to removing that line but it may be a start to figuring out the conflict, if possible. I'll do another test again once a fix is out for Bug 1.

=====

Tested this again with "geneticsreborn-1.12-1.26" and the 3 bugs still occur.

**Comment by clubpetey** [comment]
Item 1 has been reported before, and will be addressed on Issue #164 

Item 2 has been fixed with the shift-click re-write, clicking or shift-click stacks of potions works like it should.

Item 3 has been corrected in 1.27.  I have changed IDs of all potions to include the mod ID, so there will be no more conflicts.  However, this will invalidate all your existing potions, and you will receive a forge warning that there are "missing items" when you load your save games.  The warning can be safely ignored but all potions will be removed.  Sorry, but it cannot be helped.
