### ISSUE TITLE
1.26 - still cant add chorus fruit into advanced incubators

### ISSUE THREAD

**Issue by DartisXUI** [TheUnderTaker11/GeneticsReborn#177]
basically, the secondary ingredient input to the right of the ui is still filled with whatever potion youre brewing

i mentioned this as a side point for a 1.25 bug report, but seems to still be around in 1.26 - unless things have changed as far as chorus fruit negating the deficits of adding overclockers to adv incubators

**Comment by DartisXUI** [comment]
i assume your fix for collecting the processing drops after harvesting has fixed this also as you mentioned the whole shift clicking stacked potions is fixed as well?

**Comment by clubpetey** [comment]
Yes, this is fixed in 1.27 as well with the re-write of the shift-click.
