### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by RickardETW** [TheUnderTaker11/GeneticsReborn#18]
When i use Genetics Reborn on a forge server it crashes the server

here the crash log if you need it. https://jpst.it/RSo6

**Comment by TheUnderTaker11** [comment]
I will always need as much info as you can give me. From this crash report I'm pretty sure I know the exact problem, and I'll fix it when I get home in 4-5 hours.

**Comment by TheUnderTaker11** [comment]
Problem fixed, it should work now. Sorry about that, just a server only issue that slipped through. If there is any problems report them right away, I have just enough time to push this new version out and as such can't do a lot of serverside testing.
