### ISSUE TITLE
Auto-eject machine output out the bottom

### ISSUE THREAD

**Issue by clubpetey** [TheUnderTaker11/GeneticsReborn#180]
Only if there's a valid inventory of course.  This saves people from using hoppers and that means less tile entities and less lag.

**Comment by DartisXUI** [comment]
i can confirm ender io item conduits work for this as of v1.28.
this is my first server trying to automate genetics reborn, and the item conduits worked a treat until now...

they dont work properly for things like the plasmid infuser. while the item conduits do only remove the machine output, they also remove plasmids being infused at any progress level - such as 14/50

**Comment by clubpetey** [comment]
I've come up with a fix for the plasmid infuser issue., Fix in 1.30.

**Comment by clubpetey** [comment]
Because of the way the "older" blocks work, if I stop the ejecting of the plasmid until it is complete, it also means you cannot remove the plasmid using the GUI until it is complete.  I didn't like this side effect and tried a few ways around it, but it would require changing all the machines -- splitting the shared code handing inputs and output.  I've made a note for 2.0, but I'm not going to make this large of a change in this codebase.
