### ISSUE TITLE
[1.12.2] Mutated EFFICIENCY Gene resets break speed back to normal.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#181]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 3
geneticsreborn-1.12-1.27
jei_1.12.2-4.15.0.291
theoneprobe-1.12-1.4.28

=====

EFFICIENCY Gene appears to work fine however if you inject yourself with the Mutated EFFICIENCY Gene aka EFFICIENCY_4. Your break speed resets back to normal as if you didn't have the gene at all.

Using my fist to punch out a Grass Block. This is what the progress bar shows via the one probe.

Default:
5%, 11%, 16%, 22%, 27%...

EFFICIENCY:
11%, 22%, 33%, 44%, 55%...

EFFICIENCY_4:
5%, 11%, 16%, 22%, 27%...

The regular one appears to work fine but it breaks when you get the mutated one. You'll have to remove both genes & re-add the regular one in order to gain the boost again.

**Comment by clubpetey** [comment]
Yea, I complete borked the mutation calculation, I blame the Bourbon.  Fixed in 1.28.
