### ISSUE TITLE
unable to make cure

### ISSUE THREAD

**Issue by Callin55** [TheUnderTaker11/GeneticsReborn#190]
I cant make the cure for viruses and negative effects

mod: space astronomy 2

**Comment by clubpetey** [comment]
I need a little more info to investigate this.  Can you:
1. Give me the version of the GeneticReborn Mod you are using
2. Are you getting a crash?  Or just the incubator doesn't produce a result?

**Comment by clubpetey** [comment]
Closed due to inactivity.
