### ISSUE TITLE
1.28 Ender Dragon Flight Gene - Cant use Ender Dragon Basic Genes to complete it

### ISSUE THREAD

**Issue by DartisXUI** [TheUnderTaker11/GeneticsReborn#191]
i decided to skip the whole mutation process of flight from bats and the like - especially with the double jump requirement

got to the end, got a stack and a half of dragon organic matter

set up my genetics lab - automated this time round for the first time too!

i made a plasmid and set it to flight using the infuser, and put in a total of 7 dragon flight helixes.
but when i put in the dragon basic cells, they dont work like i expected them to as they do for other *naturally dropping/non-mutated* genes.

can confirm that hard mode is NOT enabled, so this should work for naturally dropped genes.

i havent tested any other genes yet - normally start with water breathing, and that will be myu next port of call
just wondered if the mod is recognising the naturally dropped flight gene as the mutation gene, and is requiring mutated 'basic' genes? (before i go and make all that mutation stuff)

**Comment by DartisXUI** [comment]
just checked, squid basic genes do in fact help complete the water breathing gene.

so not sure why the ender dragon's basic genes cant do that for flight

**Comment by DartisXUI** [comment]
Is there any info on whether this is a bug or not? I've almost finished my automation of resources, and will be going back to genetics reborn soon is all...

**Comment by clubpetey** [comment]
This is not a bug, the naturally-dropped Flight gene from the ender dragon is a mutated gene.  You do not need to mutate it, but you DO need to use Basic Mutated genes in the helix.

The Ender Dragon is the only mob that can drop Flight (unless someone overrides the config)
There are three naturally occurring mutations Flight, Invisibility and Luck.

Invisible/Luck can only be dropped by a Botania DoppelGanger.
