### ISSUE TITLE
Compatability with Genetics and Corail Tombstone

### ISSUE THREAD

**Issue by Rsslone** [TheUnderTaker11/GeneticsReborn#192]
I found an issue with Genetics "Keep Inventory" and Corail Tombstone that causes the Grave key to disappear when you respawn. When you die you see the key go into your inventory on the death screen, but it vanishes when you respawn. You should keep the key. I've fixed this by setting "Keep Inventory" to false.

Related note I also believe Spongeforge is a factor, since the issue also went away with the same mod configs but without Spongeforge.

**Comment by clubpetey** [comment]
This gene is being remove in the 1.16.x release, as it doesn't really fit the mod and there's many other solutions to keep inventory. 
 I'm closing this ticket as removing the gene will remove the conflict.
