### ISSUE TITLE
Server Crashes When Airborne Dispersal Device Unit Is Given Hopper

### ISSUE THREAD

**Issue by SummonerBunny** [TheUnderTaker11/GeneticsReborn#193]
[crash-2020-05-11_10.22.24-server.txt](https://github.com/TheUnderTaker11/GeneticsReborn/files/4610372/crash-2020-05-11_10.22.24-server.txt)

[crash-2020-05-11_11.05.14-server.txt](https://github.com/TheUnderTaker11/GeneticsReborn/files/4610392/crash-2020-05-11_11.05.14-server.txt)

Tested this after a friend crashed our server by accident. All other Genetics Reborn machines seem to be fine. The first crash log happens if you place a vanilla hopper under the Airborne Dispersal Device. The second crash log is if you place an item into a hopper that leads into the Airborne Dispersal Device -- though in that regards I've only used the splash potions from Genetics Reborn itself and have not attempted vanilla potions.

After it's triggered it requires a server reset or backup to fix, as the server will continue to crash on load.

**Comment by clubpetey** [comment]
Fixed in 1.29
