### ISSUE TITLE
1.28 Flight from ender dragon doesnt work

### ISSUE THREAD

**Issue by DartisXUI** [TheUnderTaker11/GeneticsReborn#195]
after my issue with #191 i took some time with low temp incubators to keep copying my Ender Dragon Cells over and over again to get enough Flight Genes to fill it.

Completed it.

Injected it.

Double Jumped... Nothing...

this leads me to believe my theory in #191 about the Ender Dragon's Flight Gene ~~being~~ registering as a Mutation due to the Standard Gene not accepting Ender Dragon Basic Genes like a Standard Gene should, could have some weight now - if it indeed needs the jump boost to work

**Comment by clubpetey** [comment]
Did you have Jump Boost or Teleport already in your body or in the Syringe?  One of those is still required for flight.  Starting in 1.29 you can also use No-Fall-Damage.

**Comment by DartisXUI** [comment]
no i didnt have the other genes due to the way ender dragon flight description read...
as it is a *naturally dropping gene, i didnt think it was a supposed to be a mutation*, and this issue was an error - seems i was mistaken

but considering the *OP* nature of flight in this mod, i get that it needs to be a naturally dropping mutation - thats just not how it read was all

thanks for adding no fall damage though, nice addition if you dont want the other two

**Comment by DartisXUI** [comment]
this has been open for a while now,
and just realised that it should be closed as this was explained/solved in my other post: #191
as this is a naturally dropping mutation and i didnt have the required additional genes (teleport, high jump or no fall damage), of course this wouldnt work - thats just not how the gene description read...

tl/dr - im happy for this issue to be closed
