### ISSUE TITLE
1.28 - The Return of the Duplication Bug!!! (Almost)

### ISSUE THREAD

**Issue by DartisXUI** [TheUnderTaker11/GeneticsReborn#196]
so i have found extra copies of certain items while processing my mutations but have only just now managed to replicate it

***if i put in a stack of Diamond for Resistance II then harvest the Incubator to reposistion it, i get 2 Stacks back!!!*** (basically i get 2 x whatever amount (24, 50, etc) of what ever item (organic matter, cells, mutation items like emeralds, etc) i put in before haversting)

NOTE: i havent noticed any destruction of items like the original Duplication Bug had, so I suspect this is a reprecusion of adding in the drop code i requested ages ago that you said you didnt oiutright write previously to my bringing it up... maybe somethings missing/out of place?

**Comment by clubpetey** [comment]
Fixed in 1.29

**Comment by DartisXUI** [comment]
Are you still active on the mod, or have things been affected by the events around the world?
Haven't seen 1.29 released and wondered if you've been held up...
Personal note: free diamonds, emeralds, genetic material, etc... in-game is great if you have been busy by the way...

**Comment by clubpetey** [comment]
I am still intending to update the mod, unfortunately my family has been fighting COVID for the last 4-6 weeks. as everyone got it at different times.  We are getting over the last of it, and I'll have some updates out in the next 7-10 days.

**Comment by DartisXUI** [comment]
take your time, mate... 
hope you all get better
