### ISSUE TITLE
Teleport and other genes doesnt work

### ISSUE THREAD

**Issue by SacredDarkness** [TheUnderTaker11/GeneticsReborn#197]
Today, I completed the teleport gene, and speed IV too, so, y used them, but, the teleport doesnt work (i press G and nothing happens) and speed IV doesnt applied, i have speed II but not IV

**Comment by clubpetey** [comment]
I cannot replicate this.  I'm going to close it for now, but if you can provide more information, please re-open.  It's possible this is a gene conflict, so let me know if you had any other genes active at the time.
