### ISSUE TITLE
managed to get level to get all the viruses and it seems whenever you put in a syringe in the incubator with that, it crashes

### ISSUE THREAD

**Issue by NordicGamerFE** [TheUnderTaker11/GeneticsReborn#202]
`

Time: 2020-06-19 17:22:46 CDT
--
  | Description: Updating screen events
  |  
  | java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
  | at com.theundertaker11.geneticsreborn.potions.ComplexBrew.isIngredient(ComplexBrew.java:119)
  | at net.minecraftforge.common.brewing.BrewingRecipeRegistry.isValidIngredient(BrewingRecipeRegistry.java:161)
  | at net.minecraft.inventory.ContainerBrewingStand$Ingredient.isItemValid(ContainerBrewingStand.java:200)
  | at net.minecraft.inventory.ContainerBrewingStand.transferStackInSlot(ContainerBrewingStand.java:98)
  | at net.minecraft.inventory.Container.slotClick(Container.java:246)
  | at net.minecraft.client.multiplayer.PlayerControllerMP.windowClick(PlayerControllerMP.java:566)
  | at net.minecraft.client.gui.inventory.GuiContainer.handleMouseClick(GuiContainer.java:638)
  | at net.minecraft.client.gui.inventory.GuiContainer.mouseClicked(GuiContainer.java:392)
  | at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533)
  | at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
  | at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
  | at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
  | at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
  | at net.minecraft.client.main.Main.main(SourceFile:123)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  | at java.lang.reflect.Method.invoke(Unknown Source)
  | at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
  | at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

`

**Comment by NordicGamerFE** [comment]
https://github.com/NordicGamerFE/Ocean-Outlast/issues/10

**Comment by clubpetey** [comment]
Fixed in 1.29
