### ISSUE TITLE
Client Side Crash - Incubator + Syringe with all Viral Agents (creating Black Death Potion)

### ISSUE THREAD

**Issue by boxers41** [TheUnderTaker11/GeneticsReborn#203]
Hello, 

Upon attempting to create a Black Death Potion, a client side crash occurs. After extracting and purifying the blood with all viral agents placing the syringe in the incubator crashes the client. 

Crash Report Attached.

[message.txt](https://github.com/TheUnderTaker11/GeneticsReborn/files/4876498/message.txt)

Thanks,

-Boxers41

**Comment by clubpetey** [comment]
Fixed in 1.29

**Comment by clubpetey** [comment]
Also, dupe of #202
