### ISSUE TITLE
Server Side Crash - Drinking THE CURE potion crashes Server

### ISSUE THREAD

**Issue by boxers41** [TheUnderTaker11/GeneticsReborn#204]
Hello,

Drinking a The Cure potion with all viral agents in the bloodstream creates a server side crash. 

Crash Report from Server Attached.

[crash-2020-07-05_22.23.52-server.txt](https://github.com/TheUnderTaker11/GeneticsReborn/files/4876507/crash-2020-07-05_22.23.52-server.txt)

Thanks,

-Boxers41

**Comment by clubpetey** [comment]
Fixed in 1.29
