### ISSUE TITLE
[Suggestion] Better JEI integration

### ISSUE THREAD

**Issue by aaronhowser1** [TheUnderTaker11/GeneticsReborn#206]
It would be very nice if every gene was available in JEI, with recipes etc

**Comment by clubpetey** [comment]
I am going to pass on this request for two reasons:
1. The genes that an animal can drop is editable using the config and which mods are installed. It will be different for different mod packs.
2. I find this to be a core mechanic of the mod, discovering which mobs grant you which powers.  Having it in JEI would remove some of the mystery.
