### ISSUE TITLE
real issue or anything else? incubator

### ISSUE THREAD

**Issue by TheXTrunner** [TheUnderTaker11/GeneticsReborn#207]
![Anotación 2020-08-27 032530](https://user-images.githubusercontent.com/46388285/91411001-bd883900-e815-11ea-8d20-12fb32cd4042.png)
chorus fruit slot is getting a duplicate in the first slot of potions, not allowing you to use 3 potions with chorus fruit for mutation

**Comment by clubpetey** [comment]
Fixed in PR, changes incoming this weekend
