### ISSUE TITLE
Issue: poison, wither, and weakness virus shows no symptoms

### ISSUE THREAD

**Issue by kon-Ako** [TheUnderTaker11/GeneticsReborn#210]
Forge 14.23.5.2847
Genetics Reborn v1.29
Other mods inserted are Hwyla 1.8.26-B41, InventoryTweaks-1.63, jei 4.15.0.268, journeymap 5.5.5, NBTEdit-0.7, and Optifine HD U E3

Thank you for considering my report.
Some viruses does not seem to trigger any potion effects. I checked the NBT using the NBTEdit mod and found some Strings with name of the virus under ForgeCaps>geneticsreborn:genes, so I am assuming that I successfully infected a mob with a virus. However, they don't seem to show any symptoms (like flambe does immediately) even after waiting for couple of minutes. My friends with different environment are facing identical error.

Is this intentional, or is it glitched?

**Comment by clubpetey** [comment]
Fixed in PR, changes incoming this weekend
