### ISSUE TITLE
SPEED_4 Mutation doesn't actually give Speed IV, but just Speed instead

### ISSUE THREAD

**Issue by krassell** [TheUnderTaker11/GeneticsReborn#219]
This looks to be stemming from a typo in line ` src/main/java/com/theundertaker11/geneticsreborn/event/OnWorldTickEvent.java:264`  
Where potion effect strength should likely be  
`3+GeneticsReborn.mutationAmp*2`
as opposed to  
`GeneticsReborn.mutationAmp*2`

**Comment by clubpetey** [comment]
Fixed in 1.30

**Comment by clubpetey** [comment]
Correction... fixed in 1.32, sorry, missed it in testing.
