### ISSUE TITLE
We can't inject helix in Plasmid with Plasmif Infuser V1.30

### ISSUE THREAD

**Issue by Xyphenore** [TheUnderTaker11/GeneticsReborn#221]
In 1.30 version, we can't inject Helix in Plasmid with Plasmid Infuser. Like in the screens : 
![2020-12-25_20 04 42](https://user-images.githubusercontent.com/53941443/103140956-a4bd6080-46ed-11eb-8e0a-55138eca0b53.png)
![2020-12-25_20 04 45](https://user-images.githubusercontent.com/53941443/103140958-a850e780-46ed-11eb-931a-aa04331e2f02.png)

And we can in the previous version, in 1.29

**Comment by clubpetey** [comment]
This has been hot-fixed in 1.31
