### ISSUE TITLE
Fabric Port

### ISSUE THREAD

**Issue by Jamalam360** [TheUnderTaker11/GeneticsReborn#229]
Hi,

Are you aware of any Fabric ports that are ongoing/completed and if not, would you be willing to allow me to port this mod to Fabric using the original textures etc? I believe it would make a good addition to the fabric ecosystem.

I believe the MIT license allows me to do this but I don't want to unless I have permission from the author 👍

**Comment by TheUnderTaker11** [comment]
Fabric is only 1.14 and above, and if you are not in the Discord to know, ClubPetey has a lot of plans in the works for updating past 1.12.2, so many plans it's going to look like a very different mod. Unsure what his timetable is on that so if it's gonna be long enough he might not care if you port to fabric for the higher versions in the meantime.

I'll discuss with him about it.

**Comment by Jamalam360** [comment]
Thank you,
Is it a public discord? Edit: found the hyperlink

**Comment by clubpetey** [comment]
I do not have a plan to port to Fabric.  The next update is a major overhaul of the mod for 1.16.x  but this is still 3-ish month away.  I don't see any reason not to have you work on a port, but porting the current release will be outdated quickly.

**Comment by Jamalam360** [comment]
Thanks 👍
