### ISSUE TITLE
[Suggestion] Mo' Creatures genes

### ISSUE THREAD

**Issue by RickardETW** [TheUnderTaker11/GeneticsReborn#26]
Mo' Creatures is a mod that add more mobs to minecraft. I would love to get some genes from these mobs.

**Comment by TheUnderTaker11** [comment]
I am not familiar with the mod, but I could add genes for those creatures, is there any creatures that would warrant new genes being made or are you just thinking of adding existing genes to those mobs?

**Comment by RickardETW** [comment]
i'm not sure if there any mobs there that adds something new to the table. but the existing genes would work.

**Comment by TheUnderTaker11** [comment]
Alright I'll look at it when I get home and add genes to any that would need it for my 1.0 release

**Comment by TheUnderTaker11** [comment]
As I don't know the mod I'll go through and look at the names to see what makes sense, but if you want to make a list of mobs and the genes they should have I'll add whatever is there. Just going to say though, I really don't like the wall of adfly links and ads I had to go through to get the mod.

**Comment by RickardETW** [comment]
adfly? maybe i should have mention that it on curse https://minecraft.curseforge.com/projects/mo-creatures
but i might try make that list after school.

**Comment by TheUnderTaker11** [comment]
Weird I didnt see a link to curse when iI googled it

**Comment by Nexusdog** [comment]
Does this fit with your mod? https://minecraft.curseforge.com/projects/test-tube-animals

**Comment by TheUnderTaker11** [comment]
Nexusdog, make your own suggestions thing and don't just comment on an existing one, but I'll check the mod out later, I read the desc but I'm still not sure exactly what it does.

**Comment by TheUnderTaker11** [comment]
Added support for Mo'Creatures, will be in version 1.0
