### ISSUE TITLE
A little Bug

### ISSUE THREAD

**Issue by Dracux** [TheUnderTaker11/GeneticsReborn#28]
I cant use de metal Syringe becouse it say "It is disabled in the config sorry"

**Comment by TheUnderTaker11** [comment]
Enable it in the config.

**Comment by Dracux** [comment]
But what is the permission to activate?

**Comment by TheUnderTaker11** [comment]
The whole point of the metal syringe is to give genes to other entities, so you have to enable that in the config.

**Comment by Dracux** [comment]
Sorry for my ignorance but I have no idea what this license is called or I should give you permission in the configuration could you tell me what the command or permission is called that I should activate?

**Comment by Dracux** [comment]
I already found sorry for the inconvenience very many gradias by the way your mod is great you thought to add more genes to mods like mo creatures or lycanites mobs? That do not allow for example to launch lasers as some lycanites mobs do or leave a path of flames like the nightmares of mo creatures?

**Comment by TheUnderTaker11** [comment]
I added genes for most of the mo creatures mobs, but no new ones, just the vanilla ones. Besides, leave all suggestions in a new issue marked as such.
