### ISSUE TITLE
Loosing Genetic Improvements on Death

### ISSUE THREAD

**Issue by godrage** [TheUnderTaker11/GeneticsReborn#29]
playing Invasion 1.0.5 -> died -> no more speed/strength :(

is this intented; im sorry if this issue is misplaced, but i didnt really find a better place to question for it 👍

**Comment by TheUnderTaker11** [comment]
There is a config option to keep genes that I assume is off.

**Comment by LatentDesire** [comment]
Is this the default?

**Comment by TheUnderTaker11** [comment]
No it is not default, but he is using the invasion pack.

**Comment by LatentDesire** [comment]
Thought this was the case. Thanks for clarifying.

**Comment by TheUnderTaker11** [comment]
Closing this due to it being a non-issue.
