### ISSUE TITLE
[Suggestion] Cyberware

### ISSUE THREAD

**Issue by LatentDesire** [TheUnderTaker11/GeneticsReborn#30]
If you're familiar with Deus Ex: Human Revolution, you'll know that the main character's genes are very important as they allow for adding augments without the pricy anti-rejection drug. 

As for the Cyberware mod, you can only install so many augments before your tolerance gets into the red, which means that your body will reject the augments and you will take damage until you die. However if you have Neuropozyne, the anti-rejection drug mentioned above, you will have about a minecraft day until you need to redose yourself. 

While there is an option for an augment that replicates a similar effect to the above character's genes in the Cyberware addon mod "WIRED: More Augs", I feel this mod would be a better fit for it's purposes. So an anti-rejection gene as a very rare gene from Cyberzombies would be a good idea. (Along with the regular genes one would get from a zombie.)

**Comment by TheUnderTaker11** [comment]
I'll look into it.

**Comment by LatentDesire** [comment]
Cool.

**Comment by clubpetey** [comment]
Closed, as this mod is not available for 1.12 See Issue #65
