### ISSUE TITLE
[Suggestion] Bioluminescence 

### ISSUE THREAD

**Issue by LatentDesire** [TheUnderTaker11/GeneticsReborn#31]
Suggestion for a gene which makes the player a light source. Perhaps not as powerful as a torch, but enough that the grue from the Grue mod will die if it moves close to the player. Would also be handy for caving. I'm thinking perhaps you would get this from a blaze. Maybe some way to edit what color you glow? Though that would probably require add a whole new mechanic/machine to the mod.

**Comment by TheUnderTaker11** [comment]
Not sure how much lag that would cause to try and have a light source following the player, the overhead might not be worth it. Regardless I'll eventually take a look at this and if anything add it as a gene disabled by default.

**Comment by LatentDesire** [comment]
I'd imagine it would work functionality similar to the dynamic lights mod. I'm sure they'd let you pick their brain when you take a look at this more.

**Comment by darthvader45** [comment]
Since Dynamic Lights is now a part of Optifine, you'd have to talk to sp614x.

**Comment by clubpetey** [comment]
Released in 1.14
