### ISSUE TITLE
[Suggestion] Molt skin and Absolute Defense. 

### ISSUE THREAD

**Issue by LatentDesire** [TheUnderTaker11/GeneticsReborn#32]
Got these ideas from Assassination Classroom. Both of these are essentially a save from death mechanism (except from starvation) With Molt skin, when the player would die, they instead "molt" off their skin and move to a solid block a few blocks away while leaving behind a translucent copy of their skin at their previous position. It should ideally take aggro while the player slips away. (It's unmoving with maybe 5 hearts until it's destroyed.) A downside to having this gene is that the player would move slower in water and it can only be used once per minecraft day. (So 20 minute cooldown.) I'm thinking you should be able to get this from a slime (since they split apart). 

The second idea is another save from death ability in which shrinks a player down and puts them in an impenetrable clear shell for 10 minutes. While in this state, the you cannot move and cannot be killed. You can however be moved/pushed around. I say 10 minutes since if you were being attacked outside at night, this would keep you safe until daylight. (At which time, hopefully, whatever is trying to kill you will burn to death.) Should a player have both genes, the molt skin ability takes priority. The cooldown for this ability should be about 3 minecraft days (so about an hour). I think this would be an ability gotten from a shulker, since they have shells after all. (And getting to end cities is the very end game in vanilla.)

**Comment by TheUnderTaker11** [comment]
For the first, if anything I would probably go with a phoenix type gene, or a split in half and only have half your max health until you die again type thing.
On the second, it sounds more annoying than it is worth for me and the player.

**Comment by LatentDesire** [comment]
Those both sound like good ideas for separate genes. Variety being the spice of life and all that. Not sure where you'd get the phoenix type, but the other one does sound like a more appropriate one for a slime.

Though I do still like my idea for molting and leaving behind a decoy type of idea. It's sort of like how certain lizards can detach parts of their tail and later regrow it to escape predators. (Maybe something gotten from the reptile mod?)

The other one actually fits shulkers rather well in my opinion, as they are largely stationary and have a large defense boost while inside their shells.  I suppose having a short range teleport, like they do under certain situations, could be part of the gene, or even another possible provider of a teleportation gene (along with endermen/Ender mites).

**Comment by Mekhi-Uchiha** [comment]
That first idea sounds AWESOME. the second one is ok, but the first one sounds amazing. I hope they use it.

**Comment by clubpetey** [comment]
Will be working on the first concept and attaching it to a slime.  Will probably not do the translucent player unless I can find something easy, but will have some sort of entity.

**Comment by clubpetey** [comment]
Went with an actual slime appearing that draws aggro.  Someone with more rendering talent can help me create a ghost player. :)
