### ISSUE TITLE
Console Spam?

### ISSUE THREAD

**Issue by Darkosto** [TheUnderTaker11/GeneticsReborn#33]
It looks like Genetics Reborn is causing a lot of spam when the Cell Analyzer is placed down:

https://github.com/Darkosto/InvasionIssues/issues/174

Mod Version: 1.0.2
MC: 1.10.2
Forge: 2281

Thank you for looking into this!
Darkosto

**Comment by TheUnderTaker11** [comment]
Ah thanks for the report, just some print screens I used for debugging and forgot to remove, I'll fix it and upload a new version.
(I had to change the way I did a few things to allow the power usage and such to be configurable, and that was the output I used for testing)

**Comment by TheUnderTaker11** [comment]
I don't know if I changed it after that version and forgot or what, but looking I coulden't find any print screens and I wasn't having the problem, so not sure how it got into that version. New version is uploaded now.

**Comment by Darkosto** [comment]
Thanks for looking into it :)

**Comment by TheUnderTaker11** [comment]
No problem, never mind to squash a bug
