### ISSUE TITLE
[Suggestion] Exoskeleton 

### ISSUE THREAD

**Issue by LatentDesire** [TheUnderTaker11/GeneticsReborn#34]
Gotten from Spiders, this gene would provide a permanent small boost in armor rating. Maybe as much as leather armor.

**Comment by TheUnderTaker11** [comment]
Redundant. Resistance gene already exist.

**Comment by LatentDesire** [comment]
How about a percentage chance for a blow to glance off of the exoskeleton, negating damage? Possibly with an interesting effect on a player's skin?
