### ISSUE TITLE
[Suggestion] Photosynthesis gene, regen hunger in sun

### ISSUE THREAD

**Issue by TheUnderTaker11** [TheUnderTaker11/GeneticsReborn#36]
Suggested vocally to me, writing here to document.

**Comment by LatentDesire** [comment]
I had thought of something like that but wasn't sure if it was planned yet. Maybe something gotten from Creepers? They seem plant-y, right?

Oh, or from Foliath from Mowzie's Mobs.

**Comment by TheUnderTaker11** [comment]
Added, will be in next update.
