### ISSUE TITLE
need help don't know if it's a bug or not

### ISSUE THREAD

**Issue by zadric** [TheUnderTaker11/GeneticsReborn#37]
The blood purifier doesn't seem to work? it's power is full and the syringe doesn't get processed
and also the plasmid infuser, how do you get them to working?

**Comment by TheUnderTaker11** [comment]
https://github.com/TheUnderTaker11/GeneticsReborn/wiki

If the problems persist make sure to give me more information, such as mod and minecraft version.

**Comment by zadric** [comment]
Mod version: geneticsreborn-mc1.11.2-v1.05
minecraft version: 1.11.2

**Comment by TheUnderTaker11** [comment]
Working on it, expect a fix soon.

**Comment by TheUnderTaker11** [comment]
Blood purifier has been fixed, but I can not find a problem with the plasmid infuser, mind being more specific?

**Comment by zadric** [comment]
it may not have been a bug, I just don't know how to get the plasmid infuser to work, the dna helix won't get processed. and i've followed the process from the start. first cell analyzer, then dna extractor, and then dna decryptor. but at the plasmid infuser it didn't get processed. and I know if it's like the advanced genetics it would need a few basic dna or the same dna to get it processed but i just don't know how.

**Comment by zadric** [comment]
ok nvm i just found out how. so the only problem is the blood purifier

**Comment by TheUnderTaker11** [comment]
Alright then problem is solved, new version will be uploaded as soon as I compile it.

**Comment by zadric** [comment]
Oke thx :D
