### ISSUE TITLE
[Suggestion] Config for adding existing genes to new mobs

### ISSUE THREAD

**Issue by shadowbolt79** [TheUnderTaker11/GeneticsReborn#38]
Because there are several mods that new mobs, or replace existing ones, being able to quickly add mobs to a mod pack would be helpful. Such as Animania; which replaces existing farm animals with their own copy, and then has several different breeds of them on top of that; makes it impossible to get genes based on horses, pigs, sheep, cows, chickens, ect.

**Comment by TheUnderTaker11** [comment]
Hm I do have a super easy to use API method for that [here](https://github.com/TheUnderTaker11/GeneticsReborn/blob/master/src/main/java/com/theundertaker11/GeneticsReborn/api/capability/genes/MobToGeneRegistry.java#L79), but I do see how a config option would be useful. I'll see what I can do about adding a list to the config you can add stuff to.

**Comment by Keetarin** [comment]
So how's the config stuff coming along? This would be super helpful after all.

**Comment by clubpetey** [comment]
Turns out, this actually exists.  Look in config/GeneticsReborn/MobAdditions.json  You will need to know the name of the mob you want to add genes to.  

Version 1.12 adds the ability to add more than 3 genes to any given mob and the options to disable the default assignments.
