### ISSUE TITLE
Glass Syringe don't inject blood

### ISSUE THREAD

**Issue by AndreiTS** [TheUnderTaker11/GeneticsReborn#4]
After doing all steps I tried to inject the Syringe with "Shoot Fireballs" effect but it didn't work, i was in survival. i don't know if i'm doing something wrong

**Comment by AndreiTS** [comment]
edit: found another issue in plasmid injector, it don't work
![2017-01-11_16 19 30](https://cloud.githubusercontent.com/assets/13489837/21860893/d9bd02be-d819-11e6-85cd-a55c04eddd3c.png)

**Comment by TheUnderTaker11** [comment]
Did you purify the blood? The blood has to be purified in the blood purifier for any step you plan to do. Also new version out with recipes now (I'm assuming you are one of the 4 that downloaded the no recipes version)
I made this mechanic to mimic how it was done in 1.7.10. The tooltip should tell you if it is contaminated or not if you put your mouse over it.

**Comment by AndreiTS** [comment]
Yes I did, but sometimes it  just don't work. (i'm the first lol)

**Comment by TheUnderTaker11** [comment]
I just tested with the resistance gene and it worked perfectly, I'm going to need some more info about what is going wrong then.

**Comment by AndreiTS** [comment]
https://youtu.be/cWae7fSs-qU

Update to recipe version.

**Comment by TheUnderTaker11** [comment]
Well... I honestly have no idea what is wrong. Thank you so much for the video, I recreated exactly what you did and it didn't mess up at all. This might sound stupid but did you double check the machine is getting power? It might be a GUI glitch showing power it doesn't actually have?
What other mods do you have, and is there any other things you think might be messing with it that I didn't account for? Like I said, I'm kind of stumped right now since I can't recreate this problem.
(And my testing hasn't been in the Dev environment, I made sure that woulden't be something that could confuse us.)

**Comment by AndreiTS** [comment]
Yes the machine is powered by a creative capacitor bank from enderio.
I'm using: BetterFps 1.3.2, Endercore 1.10.2-0.4.1.62, EnderIO 1.10.2-3.1.157, jei 3.14.2.401, Optifine 1.10.2-HD-U-D4, TheOneProbe 1.3.3 and TheOneProbeAddons 0.9.0

**Comment by AndreiTS** [comment]
How i said before it worked like 2 times in 5. (tested with chicken and blaze )

**Comment by TheUnderTaker11** [comment]
OH my god the answer was staring me in the face the whole time. I forgot I added this mechanic, but if your blood already has the gene in it, it won't try and inject the plasmid again. Is this the solution? I do have a debugger so you can remove the genes before you take your blood each time.

**Comment by AndreiTS** [comment]
Yeah, it worked now. But i can't use the  Syringe , I shift-right click to inject in survival mode but it doesn't do anything.
OBS: if you use the cheat tool you are not able to fly in creative anymore, you have to switch to survival and then to creative to work again.

**Comment by TheUnderTaker11** [comment]
Thanks for telling me, I'll make sure to do a creative mode check.
What does "I shift-right click to inject in survival mode but it doesn't do anything." mean? Like the Cheat tool or the syringe?

**Comment by AndreiTS** [comment]
The syringe, I can't inject it to get effects, it doesn't do anything.

**Comment by TheUnderTaker11** [comment]
Wait so if you are not shifting does it still work?

**Comment by AndreiTS** [comment]
Ops, I need to purify again sorry for making you waste your time.

**Comment by TheUnderTaker11** [comment]
Alright no problem, thank you for the report, even if it was a non problem I now updated my wiki to make sure future people know that!

**Comment by NerdCraft** [comment]
can this "mechanic" be disabled? like if I want more effects
