### ISSUE TITLE
Can't Inject self with syringe?

### ISSUE THREAD

**Issue by Pwnobbypure** [TheUnderTaker11/GeneticsReborn#40]
I added the Enderman teleport gene to the DNA Plasmid until it was completely "filled". I then combined it with my blood, but when I shift right click it doesn't inject myself with the blood? Am I doing something wrong?

**Comment by TheUnderTaker11** [comment]
Does it say it is purified?

**Comment by Pwnobbypure** [comment]
After I add the gene to the plasmid it becomes contaminated, is it a chance thing that it says purified or something? Tried 3 times and each time the purified blood got contaminated when adding the gene

**Comment by Pwnobbypure** [comment]
...that it STAYS* purified...

**Comment by TheUnderTaker11** [comment]
You have to purify it after every step.

**Comment by Pwnobbypure** [comment]
So the process after obtaining the complete plasmid would be to combine it with the purified blood, then purify it again?

**Comment by TheUnderTaker11** [comment]
It is all explained in the wiki, but yes.
Just read the tooltip that says if it is purified or not. If it isn't,
purify it.

**Comment by Pwnobbypure** [comment]
Alright thanks, I'll give it a shot

**Comment by TheUnderTaker11** [comment]
Assuming it worked and closing issue.
