### ISSUE TITLE
Cannot Share

### ISSUE THREAD

**Issue by Nagatna** [TheUnderTaker11/GeneticsReborn#43]
I have been playing on Space Astronomy 2 with some friends. I started doing Genetics getting quite a few nice things in it. When I went to share these abilities with my friend, he could not use the syringe on himself. Is he just being silly or is something stopping him?

**Comment by TheUnderTaker11** [comment]
Check config

**Comment by Nagatna** [comment]
Will do.

**Comment by TheUnderTaker11** [comment]
Closing due to time, no response. Open a new thread of the bug persist, but I doubt you're still even playing the same pack.
