### ISSUE TITLE
can't use metal syringe on mobs???

### ISSUE THREAD

**Issue by shadowcoderx311** [TheUnderTaker11/GeneticsReborn#46]
when I hit a sheep it pops up in the text: "That is disabled in the config, sorry".
also when I go to the mod options the disable button for this mod is highlighted but the config is grayed out. how can I fix this? 1.10.2 minecraft version.

**Comment by TheUnderTaker11** [comment]
Solved already, but answer if someone else in inexperinced enough to have this problem is that you need to go to the actual config file and edit it with notepad or some text editor.
