### ISSUE TITLE
Plasmid Injector isn't accepting any Plasmids

### ISSUE THREAD

**Issue by mahilo3550** [TheUnderTaker11/GeneticsReborn#51]
I have one plasmid with Fire Proof and one with Poison Immunity and neither will go into the Plasmid Injector....???

**Comment by TheUnderTaker11** [comment]
More info.    
Did you complete both plasmids? Maybe post a few screenshots to clarify your problem? Pretty vague.

**Comment by mahilo3550** [comment]
Nevermind I got it.
