### ISSUE TITLE
Plasmid Infuser not working.

### ISSUE THREAD

**Issue by Gatt06** [TheUnderTaker11/GeneticsReborn#52]
I am playing Minecraft 1.12.2, and when I put a DNA Helix into the Plasmid Infuser, nothing happens. The machine is powered by an RF device.

**Comment by TheUnderTaker11** [comment]
A bit more info? Which helix, is the plasmid you have in there already set to a certain gene, maybe a screenshot or two would help as well.

**Comment by Gatt06** [comment]
I figured it out from that. I didn't know I needed a plasmid already in the infuser. Thanks.
