### ISSUE TITLE
Plasmid Injector not working.

### ISSUE THREAD

**Issue by Gatt06** [TheUnderTaker11/GeneticsReborn#53]
I have a completed Wooly DNA Plasmid and a Glass Syringe of purified blood. When I put the Plasmid and the syringe into the slots, nothing happens. My version is 1.12.2.

**Comment by alothmanmoe** [comment]
1. just reopen the old issue instead of a new one, isn't really that big of a deal
2. please make sure you read the wiki on how to do it correctly i have testing while porting the mod and in a modpack called unity and its worked perfectly fine from what i did
3. screenshots and more info are needed, thats too vague 
```
Now that you have a finished plasmid, you will want to make two more machines, the Plasmid Injecter and the Blood Purifier. You will take a syringe with blood in it and stick it in the purifier, after that is finished combine it with the finished plasma in the Plasma Injecter. Then after that Purify the blood one more time and it is ready to be put back into your bloodstream.

Right click the syringe and boom, you now have that gene! (Some might take a second or two to come into effect.)
```

**Comment by Gatt06** [comment]
I've done everything the wiki has said to do. Screenshots: 
![2017-12-12_22 00 27](https://user-images.githubusercontent.com/32237085/33921219-09813a6c-df88-11e7-9a24-78910ba3bdf7.png) 
![2017-12-12_22 00 30](https://user-images.githubusercontent.com/32237085/33921222-0f6d7c88-df88-11e7-9e5b-b389759df86e.png)
![2017-12-12_22 00 33](https://user-images.githubusercontent.com/32237085/33921227-13003f2a-df88-11e7-8f98-1db607bac35d.png)
And sorry I'm doing this wrong, I'm new to this website and this mod.

**Comment by TheUnderTaker11** [comment]
If you already have the gene it won't try and add it to your blood again.

**Comment by Gatt06** [comment]
I injected myself with blood from a sheep earlier by accident, but I didn't add the plasmoid to it.

**Comment by TheUnderTaker11** [comment]
How would you inject yourself with sheep blood? You can only use a metal syringe to even get it, which you can't put into yourself.

**Comment by TheUnderTaker11** [comment]
Closing because issue opener stopped responding.
