### ISSUE TITLE
Unable to use scraper on Ender Dragon

### ISSUE THREAD

**Issue by mahilo3550** [TheUnderTaker11/GeneticsReborn#55]
Version: 1.12-v1.08. Attempted using the Metal and Advanced Scraper on the Ender Dragon and was unable to produce any organic matter or inflict any damage on the mob. How are you suppose to get the Ender Dragon gene when you cannot obtain any of its' organic matter?

**Comment by alothmanmoe** [comment]
I have just gone back and fixed this, will post an updated version on curse soon!
