### ISSUE TITLE
AE import busses remove items from input slot

### ISSUE THREAD

**Issue by JelleDijkhuizen** [TheUnderTaker11/GeneticsReborn#57]
If you connect an import bus the the machines. It will import the items from the input slot instead of the output slot. On MC 1.12.2 and v1.08

**Comment by TheUnderTaker11** [comment]
Did you connect it to the right or bottom side of the machine?

**Comment by JelleDijkhuizen** [comment]
I tried the top and the back. But if i understand you correct i have to connect them to the bottom or right side?

**Comment by TheUnderTaker11** [comment]
Yes. Only output sides are the bottom and right. Rest are input.
