### ISSUE TITLE
Incompatability with Animania

### ISSUE THREAD

**Issue by GeminiMarshdevil** [TheUnderTaker11/GeneticsReborn#58]
none of the farm animals work with genetics reborn, having already talked to the animania mod author and they assure me everything that could identify a cow as a cow is being done with the animania cows. genetics reborn simply isnt listening and because they arent vanilla cows, you cant scrape ability genes off of them, only generic nothing genes are being produced. this same problem affects all passive mobs. 

i am willing to offer any support you may need in fixing this incompatibility with server hosting and bug testing team support. just give me a msg on my discord: https://discord.gg/5FPK6v9

**Comment by TheUnderTaker11** [comment]
[Link to the API method to add another mob](https://github.com/TheUnderTaker11/GeneticsReborn/blob/1.12/src/main/java/com/theundertaker11/GeneticsReborn/api/capability/genes/MobToGeneRegistry.java#L76)    
How to use it is explained in code, and many examples are given in the same class above it.    

Either abused_master can add in-mod compatibility, or the mod author of animania can add support for his own animals. (Third option being a super duper small and easy to make compatibility mod to connect them both. Might be a viable option for server owners.)

**Comment by alothmanmoe** [comment]
It's sad to say but Animania support won't be added any time soon by genetics reborn anyways, if you could get the authors to add the method to the registry of each mob that'd work out great but as of now each mob has like a hundred different variants which is ridiculous and i don't plan on spending the time myself adding each one in
