### ISSUE TITLE
Help to run MOD

### ISSUE THREAD

**Issue by lobezno1969** [TheUnderTaker11/GeneticsReborn#61]
How do I make the machines work, what source of energy do they use? I have tried everything and they do not work ... HELP !!!

**Comment by alothmanmoe** [comment]
The machines run on FE(Forge Energy), large amounts of mods support this, one that i can think of at the top of my head is thermal, they have FE support

**Comment by lobezno1969** [comment]
Hello again, sorry for my incompetence but I have no human way of solving the problem. I use the MOD "energyconverters_1.12.1-1.0.1.2" (theoretically compatible), but I have no way to operate the Genetics Reborn machinery. I have tried all the compatible sources of energy and they do not work or I do not make them work ....
