### ISSUE TITLE
[bug][REPEAT OF #55] Unscrapable Dragon

### ISSUE THREAD

**Issue by Rightfuldeathray** [TheUnderTaker11/GeneticsReborn#62]
I cant seem to scrape samples from the ender dragon, in survival or creative, or under any circumstance. This is a vanilla resurrected dragon I'm trying this on. I am using the 1.12 version of this mod, I'm not sure if this is a compatibility issue since another mod might be altering the dragon in someway, but I wouldn't think so since the scraper works on modded entities yielding only basic genes, however because of my uncertainty I have included a list of all mods I'm using. Draconic Evolution is installed 

Minecraft Forge v: 14.23.2.2627
AetherLegacy v: 1.12.2-v2.0
AngelRingToBauble v: 1.12-0.31.50+d4e654e
AppleCore v: mc1.12.2-3.1.1
AppliedEnergistics2 v: rv5-stable-11
AutoRegLib v: 1.3-16
BadWitherNoCookie-Reloaded v: 1.12.2-2.12
Baubles v: 1.12-1.5.2
BetterBuilder'sWands v: 1.12-0.11.1.245+69d0d70
BetterFPS v: 1.4.8
BiblioCraft v: [v2.4.3][MC1.12.0]
BloodMagic v: 1.12.2-2.2.7-90
Botania v: r1.10-353
Brandon'sCore v: 1.12-2.4.0-152-universal
Buildcraft v: 7.99.15
BuildcraftCompat v: 7.99.14
ChickenChunks1.8+ v: 1.12.2-2.4.1.71-universal
Chisel v: MC1.12.2-0.2.0.31
CodeChickenLib1.8+ v: 1.12.2-3.1.6.339-universal
CoFHCore v: 1.12.2-4.3.10.5-universal
CoFHWorld v: 1.12.2-1.1.1.12-universal
CommonCapabilities v: 1.12-1.4.0
ConnectedTexturesMod v: MC1.12-0.2.3.12
CosmeticArmorReworked v: 1.12.2-v1
CyclopsCore v: 1.12.2-0.11.5
DecoCraft2 v: 2.5.5_1.12.2
DietHoppers v: 1.1
DoomlikeDungeons v: 1.11.1-MC1.12.2
DraconicEvolution v: 1.12-2.3.10.284-universal
EnderStorage1.8+ v: 1.12.2-2.4.2.126-universal
EnderTanks v: 1.12.0-1.6.5
ExtraUtilities v: 1.12-1.7.5
ExtraCells2 v: 1.12.2-2.5.11a48
GeneticsReborn v: 1.12-1.08
GraveStoneMod v: 1.10.1
Guide-API v: 1.12-2.1.5-60
HealthAndHungerTweaks v: 1.12-2.1.1
IntegratedDynamics v: 1.12.2-0.11.9
IntegratedTunnels v: 1.12.2-1.5.5
InventoryTweeks v: 1.63
IronBackpacks v: 1.12.2-7.0.40.824
Jglrxavpok'sUncraftingTable v: 1.8-beta6
JourneyMap v: 1.12.2-5.5.2
JustEnoughItems v: 1.12.2.4.8.5.147
JustEnoughResources v: 1.12.2-0.8.5.27
Mantle v: 1.12-1.3.1.21
Mekanism v: 1.12.2-9.4.3.330
MekanismGenerators v: 1.12.2-9.4.3.330
MekanismTools v: 1.12.2-9.4.3.330
MoreOverlays v: 1.13-mc1.12.1
OMLib v: 1.12.2-3.0.0-138
OpenBlocks v: 1.12.2-1.7.6
OpenModsLib v: 1.12.2-0.11.5
OpenModularTurrets v: 1.12.2-3.0.0-236
OptiFine v: 1.12.2_HD_U_D1
Psi v: r1.1-59
QuickLeafDecay v: MC1.12.1-1.2.4
RealmOfTheDragons v: 1.12.2(TheRPGAdventurer)-1.0
RedstoneFlux v: 1.12-2.0.1.2-universal
ReliquaryV1.3 v: 1.12.2-1.3.4.757
ReWIRED v: 1.0.3
RoboticParts v: 1.12.2-0.2.10.10
RoguelikeDungeons v: 1.12.2-1.8.0
ShetiPhianCore v: 1.12.0-3.5.6
StairwayToAether v: 1.12_v08
ThermalDynamics v 1.12.2-2.3.10.4-universal
ThermalExpansion v: 1.12.2-5.3.10.15-universal
ThermalFoundation v: 1.12.2-2.3.10.6-universal
TinkersConstruct v: 1.12.2-2.9.1.65
TorchMaster v: 1.12.2-1.6.1.53
ToroHealthDamageIndicators v: 1.12.2-11

**Comment by alothmanmoe** [comment]
Just went back and fixed this, will have an update out soon!
