### ISSUE TITLE
[Suggestion] Better documentation

### ISSUE THREAD

**Issue by Rightfuldeathray** [TheUnderTaker11/GeneticsReborn#63]
info on specific genes and how they can be obtained would be super helpful on the wiki, along with more information on items and blocks, and if they are currently obtainable.

**Comment by TheUnderTaker11** [comment]
All genes are obtained in the same way.

**Comment by TheUnderTaker11** [comment]
And to add to that, each gene's page has a list of what mobs drop them, so if there is something specific you can open a new issue and I will look into it.
