### ISSUE TITLE
New Genetics Gene/Mod Integration

### ISSUE THREAD

**Issue by Tellik** [TheUnderTaker11/GeneticsReborn#65]
Would it be possible to include integration with Robotic Parts (Cyberware port to 1.12).

My idea was basically to be able to acquire a gene from Cyberzombies that provided a boost to a player's tolerance 

A slightly different idea was that the gene could naturally produce Neuropozyne, (So the player wouldn't need to inject themselves with it manually to get the Anti-Rejection buff.)

If both of those ideas are feasible, ReWired is an addon for Robotic parts adds in a CyberSkeleton which would allow both genes to be acquired.

**Comment by clubpetey** [comment]
Will look into this.  Also see:
https://github.com/Flaxbeard/Cyberware/issues/115
