### ISSUE TITLE
Anti Plasmid

### ISSUE THREAD

**Issue by PotFlux** [TheUnderTaker11/GeneticsReborn#66]
Can't craft anti plasmids nor find any information on them. 
I wanted this mod in my modpack, but if it's incomplete, I can't be having it.

**Comment by TheUnderTaker11** [comment]
Only thing incomplete is your issue. MC and mod version should be included.

**Comment by CaptainCygni** [comment]
There _still_ appears to be no way of crafting or obtaining an anti plasmid. Is this an oversight or are you trying to think of something?

Also your previous statement does not make much sense. Are you trying to imply that he is **wrong** and that there is no issue?

**Comment by TheUnderTaker11** [comment]
The recipe is just like the plasmid but with a fermented spider eye in the
middle. That or if is one plasmid with a fermented spider eye shapeless.
Dont remember which.

**Comment by rthepenguin** [comment]
Just tried both of the above methods; neither worked. Mod v1.09 MC v1.12.2

**Comment by GamertechAU** [comment]
MC 1.12.2
GR 1.09

Same thing, anti-plasmid doesn't have a recipe, and even after adding one with crafttweaker, it doesn't craft with a completed plasmid to form a completed anti-plasmid. So there doesn't seem to be a way to remove genes atm.

**Comment by clubpetey** [comment]
fixed in next release.
