### ISSUE TITLE
Cell Analyzer Random Destruction

### ISSUE THREAD

**Issue by ArmageddonX430** [TheUnderTaker11/GeneticsReborn#69]
Genetics Reborn 1.09
Minecraft 1.12.2

When I place an organic matter into the cell analyzer, my cursor turns into 64 of that organic matter, 64 of that matter goes into the analyzer, and something random on my hotbar blinks out of existence.  First time it was my fully upgraded/enchanted Draconic Staff of Power.  That took a while in creative to get back to what it was.  Then I did a session backup and tried again.  This time my upgraded accustomed-level Cobalt Mattock was annihilated.  Thankfully restoring my backup worked.

This might be the least surprising thing you've ever heard, but I think I'm not going to use this mod in it's current state.

**Comment by clubpetey** [comment]
Latest PR should have fixed this issue.  If you are still experiencing it, let me know.
