### ISSUE TITLE
here is another small bug 

### ISSUE THREAD

**Issue by mcpecommander** [TheUnderTaker11/GeneticsReborn#7]
I do not know if this is meant to happen but it is annoying as hell . so every time I get a blood syringe and purify it with the purifier , it becomes purified but the problem that it says shift right click to inject and you can inject yourself if only pressed right click on its own so if I accidently right clicked the purified syringe while holding it , I end up injecting myself with blindness for 2 seconds (I know that the blindness effect is on purpose to represent the change that is happening to the body)

**Comment by TheUnderTaker11** [comment]
You are right, I see now that I check the player is not shifting when you try and pull it out, but I never actually check if they are to put it back in. In 6-7 hours I will be able to fix this, since it will only take a line or two of code.

**Comment by TheUnderTaker11** [comment]
Alright problem is fixed but I won't push out another update just for this one, it will have to wait until I get the mob genes working
