### ISSUE TITLE
Scare Creeper gene not working

### ISSUE THREAD

**Issue by adamanek** [TheUnderTaker11/GeneticsReborn#71]
Give the mod and Minecraft version along with the issue or it will be closed and ignored.

Hey, using Minecraft 1.12 genetics reborn full release version.

The Scare Creeper gene from Ocelots doesn't seem to be working. I've injected myself with it (followed the steps, had the completed plasmid, injected it into purified blood, purified again and then injected myself) but creepers are still not running away from me and are exploding. Another proof that I actually have the gene is that I made another Scare Creeper completed plasmid but I can't inject it into purified blood (as far as I know if you already have the gene you can't inject it again, right?)

**Comment by clubpetey** [comment]
Confirmed that the in current 1.12.2 version the gene works as designed.  Note the following though:
1. The Creeper will run away when in open-spaces, if you trap the Creeper in a small place, like underground or in a small fenced-in area.  The AI can realize that there no place to run and trigger the explosion event.  There's nothing specific in the AI changes in this mod that stop the explosion, it just makes the creepers run away.

2. Other mods that overwrite mob AI can replace the custom AI in this mod if it's loaded later in sequence.  

If you are still experiencing this issue, check for other mods changing mob AI.
