### ISSUE TITLE
Minecraft server Crash

### ISSUE THREAD

**Issue by ghost** [TheUnderTaker11/GeneticsReborn#73]
https://pastebin.com/3etFBSJk

**Comment by TheUnderTaker11** [comment]
I see from the crash it is 1.10.2 correct? You have a ton of other mods, so unless you can reproduce this with either just this mod installed, or this and one or two other mods there is nothing I can do. Nothing in the crash report even points to my mod. Open a new issue if you actually pinpoint a problem. I've played extensively with the 1.10.2 version with a ton of other mods installed, so I can vouch for it's stability.
