### ISSUE TITLE
[Suggestions] Multiple Suggestions

### ISSUE THREAD

**Issue by dragonfire0612** [TheUnderTaker11/GeneticsReborn#74]
It might be beneficial to allow for injecting multiple genes onto plasmids, whether that involved using crafting to combine them, making a new machine, or simply allowing multiple genes to go onto one plasmid from the plasmid injector. 

Just a thought. Feel free to disregard if you've already thought of/tested this idea.

**Comment by dragonfire0612** [comment]
Also, would it be possible to make DNA Helices of the same Mob/Gene stack?

**Comment by clubpetey** [comment]
Multiple Genes added to a single Syringe is already supported.  You can also give yourself a set of genes, then extract your blood which will have a collection of all active genes in it.  Assuming the config setting is on, you can then give these genes to another player.
