### ISSUE TITLE
Request for crafting recipes

### ISSUE THREAD

**Issue by dragonfire0612** [TheUnderTaker11/GeneticsReborn#75]
Give the mod and Minecraft version along with the issue or it will be closed and ignored.

I am using Minecraft 1.12.2 and GeneticReborn version 1.09

Would it be possible to get a list of crafting recipes and how they are arranged to create the items? I don't like having to go into creative mode every time I need a new scraper. I apologize if this has already been asked/answered.

**Comment by clubpetey** [comment]
Version 1.15 will have craft-book support.

**Comment by TheUnderTaker11** [comment]
Even with that support I would highly recommend using a mod called JEI, it
is super convenient, and can do much more than vanilla Minecraft's thing.

**Comment by clubpetey** [comment]
Bumping to next release, adding craft-book support requires achievements, need to think up a good progression.

**Comment by Teibidh** [comment]
You could look at Patchoul instead of craft-book. Easy to create content and while you can certainly gate things behind achievements if you want it's certainly not a requirement.

**Comment by clubpetey** [comment]
After more thought, JEI seems the best option.  Adding advancements for the sake of craft-book doesn't make a lot of sense.  I don't like the idea of adding a mod dependency for Patchouli or any other guide-book like mod.  Besides, nearly every mod pack has JEI, and most people I talk to that have modded MC have JEI.  

With the next major release I will add the crafting recipes to the wiki here so they are documented somewhere.  I'll put them all on one page so if someone doesn't have JEI they can print them out.

But really, use JEI...
