### ISSUE TITLE
[Suggestion] GameStages Compatibility?

### ISSUE THREAD

**Issue by Keetarin** [TheUnderTaker11/GeneticsReborn#76]
It would be cool if you could make it so that some genes couldn't be gotten without getting to the appropriate stage.

**Comment by TheUnderTaker11** [comment]
That makes no sense. What do you mean by stage?

**Comment by Keetarin** [comment]
gamestages can be used to gate progress... Here's a [link, ](https://minecraft.curseforge.com/projects/game-stages)I'm not very good at explaining this.
Try imagining a tech pack with both your mod and agricraft in it, now imagine that in order to start gathering genes you would need to make a certain amount of progress in agricraft (i.e. researching genetics) then you could "apply that knowledge" (i.e. start your mod).

**Comment by TheUnderTaker11** [comment]
Recipes are easily changeable to gate progress? Besides that Abused might
add support for 1.12, but I wouldn't bet on it.

**Comment by Keetarin** [comment]
It was worth asking.

**Comment by Cosmicfox** [comment]
It is the modpack devs that worry about that stuff.. this guy went to the trouble of having someone put together the mod and update it. Lets keep him on that shall we. hahaha. Keep up the great work please TheUnderTaker.. ;)

**Comment by clubpetey** [comment]
Closing as recipes can be used to gate progress and genes have their own tiers.
