### ISSUE TITLE
Flying being cancelled when close to hostile mobs

### ISSUE THREAD

**Issue by yosoDev** [TheUnderTaker11/GeneticsReborn#77]
After getting the flying gene, I noticed that the flight is cancelled whenever I get close to a hostile mob. I can reactivate flight, but it is being cancelled almost right away again. When I get away from the hostile mob or kill it, I can fly normally again.

Version: 1.09 for MC 1.12.2

**Comment by TheUnderTaker11** [comment]
Im almost certain it is another mod disabling flight, and not a GR problem.
