### ISSUE TITLE
Recent issues, plasma infuser and injector same dang machine

### ISSUE THREAD

**Issue by Cosmicfox** [TheUnderTaker11/GeneticsReborn#78]
There are a few issues but mostly I cannot use the machines as the injector and infuser are exactly the same no matter what I do and it is the latest version. It is a new modpack I am putting together but never ever had any issues like this before. I tried cheating in both of them and the last unit to build is duplicated.. not allowing me to inject anything into the plasmid. 

Other issue shift right clicking almost any gene will duplicate or worse give you 3 stacks of it.. 

I absolutely love this mod and I certainly would not want it to go away. Heck I was willing to pay you guys to keep it going and maybe improve it overtime. Thanks for your efforts!

**Comment by Keetarin** [comment]
I've seen the same issue while testing it in a modpack I'm building for myself.
It's a large personal modpack (though if people ask I might ask someone to streamline & optimize it and make that a public version).

**Comment by clubpetey** [comment]
Both issues fixed in next release
