### ISSUE TITLE
[Suggestion] Reflex Gene

### ISSUE THREAD

**Issue by LLtalula** [TheUnderTaker11/GeneticsReborn#79]
I'd like to see some genetics around reactions, like
if hit, then blindness 2 at attacker
or
if enters water, then night vision at self
something of the sort.

**Comment by clubpetey** [comment]
I get where you are coming from, but the genes really apply to you the player, you don't really give the effect to others.  However the following is coming in the next release: 
- A "claws" gene that will inflict bleed when you hit a mob
- Bottles of Viral agents which are splash potions (that stack!) to inflict dramatic negative effects.
- A "thorns" gene that will damage the attacker when the player is hit.

Those together should cover a lot of what you are discussing.
