### ISSUE TITLE
[small suggestion]

### ISSUE THREAD

**Issue by mcpecommander** [TheUnderTaker11/GeneticsReborn#8]
I mean you are supposedly changing the whole body gene not just adding an effect so if you can take away the particles from the effects

**Comment by TheUnderTaker11** [comment]
I'll add that to my immediate TODO list, I was going to put it off but if it is annoying enough to make a suggestion I'll try and do that ASAP. Night vision will be easy but the others might take some effort. Either way I'll try and figure something out.

**Comment by TheUnderTaker11** [comment]
Done, easier than expected, will be in the next update.
