### ISSUE TITLE
Cannot scrape organic matter from the Ender Dragon

### ISSUE THREAD

**Issue by MikuTheWanderer** [TheUnderTaker11/GeneticsReborn#83]
Version 1.12 v1.09, playing on a server. Attempted using the Metal and Advanced Scraper on the Ender Dragon and was unable to produce any organic matter or inflict any damage on the mob. The dragon still takes damage from attacks with weapons, so I don't think it's the dragon. No matter how close I get, right clicking with scrapers does nothing. I can only attempt this when the dragon os hovering above the portal, because in flight you cannot get close enough to the dragon.

**Comment by ghost** [comment]
I have the same problem and this is very very problematic, can we give to ourself the organic matter of enderdragon ???

**Comment by TheUnderTaker11** [comment]
Looking back Abused put out a file that should of had this fix, is this still a problem? If so please comment and I will re-open this, otherwise, I'm closing it.
