### ISSUE TITLE
Plasmid Injector Not Working

### ISSUE THREAD

**Issue by Drayena** [TheUnderTaker11/GeneticsReborn#85]
![2019-08-10_02 02 09](https://user-images.githubusercontent.com/53963234/62818256-2883a680-bb13-11e9-98c9-42cdf565ba7e.png)
![2019-08-10_02 02 55](https://user-images.githubusercontent.com/53963234/62818257-2a4d6a00-bb13-11e9-9562-2385f11938cc.png)
![2019-08-10_02 02 59](https://user-images.githubusercontent.com/53963234/62818259-2b7e9700-bb13-11e9-8357-ff75c36077a6.png)
![2019-08-10_02 03 02](https://user-images.githubusercontent.com/53963234/62818260-2cafc400-bb13-11e9-939a-25345cc4c5c4.png)

It wont go in. I'm probably just doing something wrong, but I'm following the instructions given and it won't work.
"Now that you have a finished plasmid, you will want to make two more machines, the Plasmid Injector and the Blood Purifier. You will take a syringe with blood in it and stick it in the purifier, after that is finished combine it with the finished plasma in the Plasma Injector. Then after that Purify the blood one more time and it is ready to be put back into your bloodstream."
game version is 1.12.2, no I don't have any genes already injected as this is my first time using the mod in that world. I've tried looking for people with similar problems but as far as I can tell no one else is having the same problem.

**Comment by clubpetey** [comment]
The plasmid in your image is not complete, you need to add 20 bat genes that are of the type "Fly" and not "Basic genes".  each gene adds 2 to the count (where it shows 0/40)  so once the plasmid is 40/40 it can be added to the syringe.
