### ISSUE TITLE
[A big Suggestion]

### ISSUE THREAD

**Issue by mcpecommander** [TheUnderTaker11/GeneticsReborn#9]
If you can ,since I see this mod as the new marvel movie haha, you should make the syringes ,that have the gene inside them , "injectable" to other mobs too . I mean who does not want a fire immune horse that jumps higher and runs faster.
And you should add some extra genes that are not related to stat effects, like : rage which can be injected to villagers or animals to let them attack mobs and even players if they hurt them 
But I will try to add some ideas for mutating genes and other effects later once I have them clear inside my head.

**Comment by TheUnderTaker11** [comment]
Hm that would take a lot of AI changes for the rage thing or anything like that, but it's not a bad idea at all.
I had considered putting genes into other mobs but never put it on my to-do so I forgot about it. That will be a good amount of work but for sure worth it. It won't work on players though.
So my question is, do you want cloning or the ability to gives genes to animals first? Keep in mind I plan for cloning to be non-automatable in the fact that organic matter of the mob is needed to clone it

**Comment by mcpecommander** [comment]
I mean of course what suits best but if you have not started in any of cloning stuff then I suggest adding genes to mobs first

**Comment by TheUnderTaker11** [comment]
Man I wish I would of used some foresight when setting up all of this, it's probably going to be a few days or more before I get this whole thing up and running. Everything I had specific to the player I'm going to have to turn into working with EntityLiving

**Comment by TheUnderTaker11** [comment]
By the way, any suggestions on mobs I should blacklist from being able to receive genes? Only ones I have are Withers and Creepers.

**Comment by TheUnderTaker11** [comment]
Done. New version of the mod is up with the previous bug fixes as well as a new system to give other mobs genes.

**Comment by TheUnderTaker11** [comment]
Mainly did testing with horse/pig/cow and another mob or 2, so not 100% sure they all work but the genes shown in the genes list now should work.
