### ISSUE TITLE
[Suggestion] A way to remove Genes individually.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#90]
Unsure if this was suggested before and also not sure how this would work since it's... y'know the gene is in your blood stream & such but was wondering if this could be an option with a special type of syringe/item to remove a gene individually.

Say I have the More Hearts, Emerald Heart, Eat Grass, Dragon's Breath genes, I wish to remove the Eat Grass & Emerald Heart but keep the More Hearts & Dragon Breath genes.

Unless this is possible already?

**Comment by TheUnderTaker11** [comment]
Yes, using anti plasmids

**Comment by SonicX8000** [comment]
...oh, might've overlooked that. My apologies.
