### ISSUE TITLE
[Suggestion] Claws, Decreased Hunger, Night Vision From Wolf

### ISSUE THREAD

**Issue by RugbyHouse** [TheUnderTaker11/GeneticsReborn#94]
Genes that can be obtained from a wolf

**Comment by clubpetey** [comment]
Good call on night vision.  and I like a No-hunger gene.
What were you thinking "claws" would do?  Increase melee damage?  That's already covered in Strength gene

**Comment by RugbyHouse** [comment]
It would visually show claws on the player's hands and will increase damage. Like strength but better.

**Comment by DartisXUI** [comment]
Referring back to lucraftcore, heroes expansion has a gene similar to this for wolverine...

Heightened senses, health regen and claws

Sorry for commenting for two suggestions

**Comment by DartisXUI** [comment]
Claws should also add bleeding with higher tiers adding longer effect duration 
As for increasing damage, it could give strength I as well
For eg: flight also grants no fall - 2 genes in one

**Comment by clubpetey** [comment]
The next release will have Strength I and II as genes. But I like the bleed gene, that's one we don't have. It's similar to Poison, so to separate it I'll probably make bleed stack, with higher tiers having a higher chance of activation.

Regarding combo-genes, I want to stay away from pre-packaged combos, as the mod is more about developing your own gene sets.  You can also build up 3/4/5 genes and save them in a syringe, creating your own super hero.

**Comment by RugbyHouse** [comment]
Just thought of another one, Smell, you can smell both mobs, animals, any mob. The usefulness of the gene is so you can sense danger, food, and a village.

**Comment by clubpetey** [comment]
Is that like the "glowing" effect where you can see mobs with an outline?

**Comment by RugbyHouse** [comment]
Yeah, But there are different colors depending on the mob for example, Pig = Pink, Cow = Brown,
Villager = Cream Zombie = Green. And So On.

**Comment by clubpetey** [comment]
For this next release, adding the "Glowing" effect is straight forward, and I'll add that in.  The colors would be difficult with extra mobs or mod packs changing the default mobs.  I think we could do something based on the categories of passive, hostile, undead and villager.  But that's about as detailed as the colors could get.

**Comment by DartisXUI** [comment]
honestly id be happy with this - as having so many different colours would get confusing/overwhelming id imagine
