### ISSUE TITLE
[Suggestion] Increase stack size on items

### ISSUE THREAD

**Issue by clubpetey** [TheUnderTaker11/GeneticsReborn#95]
Make the Cells, DNAHelix and Organic Matter from Adv. Scraper stack if they have the same NBT data.

From Wxrlds on Discord

**Comment by TheUnderTaker11** [comment]
Helix ya we could make that stack for sure, but do to the way they are
organic matter and cellls cant be stacked from adv scraper

**Comment by TheUnderTaker11** [comment]
And if I remember correctly they do stack if from the same mob right? If
not then yea that can probably be done

**Comment by clubpetey** [comment]
Helix don't stack at all, that should be easy... I can get the organic matter from the Adv. Scraper to stack, unless you specifically don't WANT it to stack.  Cells from the same mob do stack.

**Comment by TheUnderTaker11** [comment]
Well it saves the specific mob ID for cloning, so stacking is just limited
by that.

**Comment by clubpetey** [comment]
Diamond Scraper materials do not stack, but Cells and Helix now stack.  Also, added a config option (default true) to let potions stack.  Side effect of this, you cannot shift-click potions into brewing stand...
