### ISSUE TITLE
[1.12.2] Unable to craft the Glass Syringe.

### ISSUE THREAD

**Issue by SonicX8000** [TheUnderTaker11/GeneticsReborn#99]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 2
geneticsreborn-1.12-1.15
jei_1.12.2-4.15.0.291

-----

![](https://cdn.discordapp.com/attachments/377171551155650560/640774789014880267/generebornglasssyringenorecipe.PNG)
The Glass Syringe cannot be crafted. JEI shows no valid recipe either.

**Comment by clubpetey** [comment]
Issues is something to do with the ore-dict entry for glass.  Switched to accepting minecraft:glass for now.
